<?
//
// $Id$
//
function FoundValid
   (
   $cert_num,
   $first_name,
   $last_name,
   $mode = ""
   )
   {
   $saved_error_level = error_reporting(E_ALL);
   //
   $result = mysql_query
      (
      "select 1 from " . $mode . "valid_for_lms "
      .  "   where short_cert_num='$cert_num'"
      .  "      and first_name='$first_name' "
      .  "      and last_name='$last_name' "
      )
      or die("FoundValid query failed with error:  " . mysql_error());
   //
   error_reporting($saved_error_level);
   return (mysql_num_rows($result));
   }
?>