//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace report_service_strike_team_roster {
    
    
    public partial class TWebForm_report_service_strike_team_roster {
        
        /// <summary>
        /// UserControl_common_header_bar_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_common_header_bar.TWebUserControl_common_header_bar UserControl_common_header_bar_control;
        
        /// <summary>
        /// Label_application_name_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_application_name_1;
        
        /// <summary>
        /// Image_uncredentialed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Image_uncredentialed;
        
        /// <summary>
        /// Label_application_name_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_application_name_3;
        
        /// <summary>
        /// Label_application_name_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_application_name_2;
        
        /// <summary>
        /// HyperLink_web_site control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink HyperLink_web_site;
        
        /// <summary>
        /// UserControl_static_service_strike_team_roster_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_static_service_strike_team_roster.TWebUserControl_static_service_strike_team_roster UserControl_static_service_strike_team_roster_control;
    }
}
