//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl_postcontent {
    
    
    public partial class TWebUserControl_postcontent {
        
        /// <summary>
        /// TableRow_creating_rosters_using_barcode_scanners control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TableRow_creating_rosters_using_barcode_scanners;
        
        /// <summary>
        /// TableRow_creating_rosters_using_cipherlab_barcode_readers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow TableRow_creating_rosters_using_cipherlab_barcode_readers;
    }
}
