//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace hardcopy_state_strike_team_key_personnel {
    
    
    public partial class TWebForm_hardcopy_state_strike_team_key_personnel {
        
        /// <summary>
        /// UserControl_common_header_bar_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_common_header_bar.TWebUserControl_common_header_bar UserControl_common_header_bar_control;
        
        /// <summary>
        /// UserControl_static_state_strike_team_key_personnel_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UserControl UserControl_static_state_strike_team_key_personnel_control;
    }
}
