//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace per_op_period_iap {
    
    
    public partial class TWebForm_per_op_period_iap {
        
        /// <summary>
        /// UserControl_common_header_bar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_common_header_bar.TWebUserControl_common_header_bar UserControl_common_header_bar;
        
        /// <summary>
        /// UserControl_per_op_period_iap_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_per_op_period_iap.TWebUserControl_per_op_period_iap UserControl_per_op_period_iap_control;
    }
}
