//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace state_detail {
    
    
    public partial class TWebForm_state_detail {
        
        /// <summary>
        /// UserControl_precontent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_precontent.TWebUserControl_precontent UserControl_precontent;
        
        /// <summary>
        /// UserControl_state_detail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_state_detail.TWebUserControl_state_detail UserControl_state_detail1;
        
        /// <summary>
        /// UserControl_postcontent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_postcontent.TWebUserControl_postcontent UserControl_postcontent;
        
        /// <summary>
        /// UserControl_update_progress_blocker_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_update_progress_blocker.TWebUserControl_update_progress_blocker UserControl_update_progress_blocker_control;
    }
}
