<?php
//
// $Id$
//
error_reporting(E_ALL);
//
$foundation_dir = "../foundation";
require_once("$foundation_dir/f_runmode.phtml");
$mode = RunMode($PHP_SELF);
//
require_once("$foundation_dir/f_hostname.phtml");
require_once("$foundation_dir/f_password.phtml");
require_once("$foundation_dir/f_connectselectdb.phtml");
//
?>
<html>
<body bgcolor=#FFFFFF>
<table align=center width=80%><tr><td>
<H1 ALIGN=CENTER>Weekly LMS Applications Report</H1>
<hr>
<pre>
<?php
//
//
// Connect to the database.
//
if (ConnectSelectDb(HostName(),"emsiweb_dba",Password(),"emsiweb_constituents") != "TRUE")
   {
   //
   // Fill the page out with a warning and instructions.
   //
   $msg = "Sorry, the database was temporarily offline at the time this report was attempted.\n";
   }
else
   {
   $batch_id = time();
   //
   $result = mysql_query
      (
      "update " . $mode . "lms_applicant set batch_id='$batch_id' "
      .  "where batch_id is null "
      )
      or die("Attempt to set batch_id's failed with error: " . mysql_error());
   //
   if (mysql_affected_rows())
      {
      $msg = "------------------------------\n"
           . "Weekly LMS Applications Report\n"
           . "------------------------------\n\n";
      //
      $sql = "select first_name "
         . ", middle_initial "
         . ", last_name "
         . ", cert_level_name "
         . ", email_address "
         . ", cert_num "
         . ", date_of_birth "
         . ", street_address "
         . ", city "
         . ", state "
         . ", zip_code "
         . ", home_phone "
         . ", county_code "
         . ", region_code "
         . ", be_instructor "
         . "from " . $mode . "lms_applicant left join " . $mode . "valid_for_lms on cert_num=short_cert_num and lms_applicant.cert_level_code=valid_for_lms.cert_level_code "
         . "   left join " . $mode . "cert_level_map using (cert_level_code) "
         . "where batch_id='$batch_id' ";
      $result = mysql_query($sql) or die("Select failed with error: " . mysql_error());
      $msg .= "FirstName"
         . ",MiddleInitial"
         . ",LastName"
         . ",CerNum"
         . ",CertLevel"
         . ",CertNum"
         . ",CertLevel"
         . ",EmailAddress"
         . ",DateOfBirth"
         . ",StreetAddress"
         . ",StreetAddress2"
         . ",City"
         . ",State"
         . ",ZipCode"
         . ",HomePhone"
         . ",CountyCode"
         . ",RegionCode"
         . ",BeInstructor"
         . ",Surge"
         . ",PrimaryAffiliationGroup"
         . ",SecondAffiliationGroup"
         . ",OtherAffiliationGroup"
         . "\n";
      while ($row = mysql_fetch_array($result))
         {
         extract($row);
         $msg .= '"'
            . ucfirst(strtolower($first_name))
            . '","'
            . $middle_initial
            . '","'
            . ucfirst(strtolower($last_name))
            . '","'
            . sprintf('pa%06s',$cert_num) . ($cert_level_name=='FR' ? "f" : "")
            . '","'
            . $cert_level_name
            . '","'
            . '","'
            . '","'
            . $email_address
            . '","'
            . sprintf("%06s",$date_of_birth)
            . '","'
            . $street_address
            . '","'
            . '","'
            . $city
            . '","'
            . $state
            . '","'
            . $zip_code
            . '","'
            . $home_phone
            . '","'
            . ($county_code==0 ? '02' : sprintf("%02s",$county_code))
            . '","'
            . sprintf("%02s",$region_code)
            . '","'
            . ($be_instructor==1 ? 'Yes' : 'No' )
            . '","'
            . 'No'
            . '","'
            . 'EMS'
            . '","'
            . '","'
            . '"'
            . "\n";
         }
      $msg .= "\nTo mark this batch as DONE, click here:\n"
         .  "http://www.emsi.org/lamp-app/lms-applicant/" . $mode . "weekly-applications-cleanup.phtml?batch_id=" . $batch_id . "\n";
      //
      }
   else
      {
      $msg = "No LMS applications this week.\n";
      }
   //
   // Send the report.
   //
   $email_addr = 'lms-registrar@emsi.org';
   $subject_string = 'Weekly LMS Applications Report';
   $result = mail($email_addr,$subject_string,$msg);
   }
?>
</pre>
</td></tr></table>
</body>
</html>
