//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace report_commanded_training_certificate_legacy {
    
    
    public partial class TWebForm_report_commanded_training_certificate_legacy {
        
        /// <summary>
        /// UserControl_training_certificate_legacy_control control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UserControl_training_certificate_legacy.TWebUserControl_training_certificate_legacy UserControl_training_certificate_legacy_control;
    }
}
