<style type="text/css"><!--
.defaultsetting {
	color:#009900;
	background-color:#ffffff;
	font-weight:bold;
	}
.customsetting {
	color:#990099;
	background-color:#ffffff;
	font-weight:bold;
	}
.navbar,.fdtan,.t {
	color:#000000;
	background-color:#d5d2bb;
	}
.g,.grey {
	color:#000000;
	background-color:#eeeeee;
	}
.fdblue,th,.b {
	color:#000000;
	background-color:#9eb3c7;
	}
input.submit,body,p,dl,dt,dd,td,th,li,ul,ol {
	font-family:verdana,sans-serif;
	font-size:10pt;
	}
textarea,input {
	font-family:monospace;
	}
input.submit {
	color:#000000;
	background-color:#ffffff;
	cursor:pointer;
	font-weight:bold;
	}
a.onblue {
	color:#000000;
	background-color:#9eb3c7;
	}
a.onblue:hover {
	color: #ff4444;
	background-color:#9eb3c7;
	}
a.onbrown {
	color:#cc0000;
	background-color:#d5d2bb;
	}
a.onbrown:hover {
	color: #ff4444;
	background-color:#d5d2bb;
	}
a {
	color:#cc0000;
	background-color:#ffffff;
	}
a:hover {
	color: #ff4444;
	background-color:#ffffff;
	}
.existingdata {
	color:#000000;
	background-color:#cccccc;
	}
//--></style>
