SET FOREIGN_KEY_CHECKS=0
;
SET AUTOCOMMIT=0
;
START TRANSACTION
;
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54001' , name = 'Auburn Fire Company Ambulance Service' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5707547919' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5707547919' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 137' , mail_city = 'Auburn' , mail_state = 'PA' , mail_zip_code = '17922' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06001' , name = 'Bally Community Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108452501' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108452501' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 353' , mail_city = 'Bally' , mail_state = 'PA' , mail_zip_code = '19503' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48002' , name = 'Bath Firefighters and Ambulance Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108376400' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108376400' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '121 Center St., Suite B' , mail_city = 'Bath' , mail_state = 'PA' , mail_zip_code = '18014' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06002' , name = 'Bethel Community Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '7179338934' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '7179338934' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '8170 Lancaster Ave., P.O. Box 32' , mail_city = 'Bethel' , mail_state = 'PA' , mail_zip_code = '195070032' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48003' , name = 'Bethlehem Township Volunteer Fire Company' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106940062' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106940062' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 3337' , mail_city = 'Bethlehem' , mail_state = 'PA' , mail_zip_code = '18020' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06004' , name = 'Blandon Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109267797' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109267797' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 258' , mail_city = 'Blandon' , mail_state = 'PA' , mail_zip_code = '195109702' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06005' , name = 'Boyertown Lions Community Ambulance Service, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6103672330' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6103672330' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '2 E. Second Street' , mail_city = 'Boyertown' , mail_state = 'PA' , mail_zip_code = '19512' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45002' , name = 'Bushkill Emergency Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5702231906' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5702231906' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 174' , mail_city = 'Bushkill' , mail_state = 'PA' , mail_zip_code = '18324' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48004' , name = 'Bushkill Township Volunteer Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107592274' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107592274' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '155 Firehouse Lane' , mail_city = 'Nazareth' , mail_state = 'PA' , mail_zip_code = '18064' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45003' , name = 'Central Pocono Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706292620' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706292620' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'RR. 611, P.O. Box 138' , mail_city = 'Tannersville' , mail_state = 'PA' , mail_zip_code = '18372' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39003' , name = 'Cetronia Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6103980239' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6103980239' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '7355 William Avenue, Suite 700' , mail_city = 'Allentown' , mail_state = 'PA' , mail_zip_code = '181069397' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39004' , name = 'City of Allentown EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6104377531' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6104377531' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '723 W. Chew Street 2nd Floor ' , mail_city = 'Allentown' , mail_state = 'PA' , mail_zip_code = '18102' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48005' , name = 'City of Bethlehem EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108657111' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108657111' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '540 Stefko Boulevard' , mail_city = 'Bethlehem' , mail_state = 'PA' , mail_zip_code = '180177052' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06003' , name = 'City of Reading Emergency Medical Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106556624' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106556624' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '638 Walnut St.' , mail_city = 'Reading' , mail_state = 'PA' , mail_zip_code = '196013690' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39005' , name = 'Coopersburg EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102824350' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102824350' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 162' , mail_city = 'Coopersburg' , mail_state = 'PA' , mail_zip_code = '18036' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48007' , name = 'Dewey Fire Company No. 1 Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108381677' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108381677' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '502 Durham Street' , mail_city = 'Hellertown' , mail_state = 'PA' , mail_zip_code = '180551999' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48025' , name = 'East Allen Township Volunteer Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102619196' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102619196' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '4945 Nor-Bath Boulevard' , mail_city = 'Northampton' , mail_state = 'PA' , mail_zip_code = '180679705' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48008' , name = 'Easton Emergency Squad' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102582866' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102582866' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '908 Packer Street' , mail_city = 'Easton' , mail_state = 'PA' , mail_zip_code = '180427375' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39006' , name = 'Emmaus Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109675615' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109675615' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '100 N. 6th Street' , mail_city = 'Emmaus' , mail_state = 'PA' , mail_zip_code = '180492424' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06006' , name = 'Exeter Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107797687' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107797687' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '30 Fairlane Road' , mail_city = 'Reading' , mail_state = 'PA' , mail_zip_code = '196069563' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48023' , name = 'Falck EMS DBA: Lifestar Response of New Jersey' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '9738127271' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '9738127271' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '657 Union Blvd' , mail_city = 'Totowa' , mail_state = 'NJ' , mail_zip_code = '07512' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06007' , name = 'Fleetwood Volunteer Fire Company Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109447676' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109447676' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '16 N. Chestnut St.' , mail_city = 'Fleetwood' , mail_state = 'PA' , mail_zip_code = '195220605' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54004' , name = 'Frackville Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708742955' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708742955' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '52 E. Arch Street, PO Box 15' , mail_city = 'Frackville' , mail_state = 'PA' , mail_zip_code = '17931' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54005' , name = 'Girardville Ambulance Service' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5702761261' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5702761261' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 26' , mail_city = 'Girardville' , mail_state = 'PA' , mail_zip_code = '179350026' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48013' , name = 'Global Medical Transportation Services, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107469378' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107469378' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 148' , mail_city = 'Bath' , mail_state = 'PA' , mail_zip_code = '18014' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54007' , name = 'Good Will Fire Company #1 DBA: Minersville EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5705449385' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5705449385' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '25 North Street' , mail_city = 'Minersville' , mail_state = 'PA' , mail_zip_code = '17954' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13013' , name = 'Greater Weatherly Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5704278772' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5704278772' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '400 Carbon Street' , mail_city = 'Weatherly' , mail_state = 'PA' , mail_zip_code = '182551423' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06009' , name = 'Hamburg EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6105625562' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6105625562' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 186' , mail_city = 'Hamburg' , mail_state = 'PA' , mail_zip_code = '195260186' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48010' , name = 'Hanover Township Volunteer Fire Company #1' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108672103' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108672103' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '100 Stoke Park Rd.' , mail_city = 'Bethlehem' , mail_state = 'PA' , mail_zip_code = '18017' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48011' , name = 'Hecktown Volunteer Ambulance Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107592594' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107592594' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 22106' , mail_city = 'Lehigh Valley' , mail_state = 'PA' , mail_zip_code = '180022106' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54008' , name = 'Hegins Area Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706823598' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706823598' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 678' , mail_city = 'Valley View' , mail_state = 'PA' , mail_zip_code = '179830678' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48024' , name = 'Hospital Ambulance LLC dba: Eagle Medical Transport' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '9089964019' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '9089964019' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '475 South St.' , mail_city = 'Morristown' , mail_state = 'NJ' , mail_zip_code = '07960' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39008' , name = 'Interstate Nursing Services Inc. DBA: Whitehall Medical Transport Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102622403' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102622403' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '4119 Redbud Dr. W' , mail_city = 'Whitehall' , mail_state = 'PA' , mail_zip_code = '18052' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48012' , name = 'Klecknersville Rangers Volunteer Fire Company' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108371901' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108371901' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '2718 Mountain View Drive' , mail_city = 'Bath' , mail_state = 'PA' , mail_zip_code = '18014' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06204' , name = 'Kutztown Area Transport Service, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106833012' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106833012' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '87 S. Kemp Road' , mail_city = 'Kutztown' , mail_state = 'PA' , mail_zip_code = '19530' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '46071' , name = 'L & P Care Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'Cardinal Drive' , mail_city = 'Birdsboro' , mail_state = 'PA' , mail_zip_code = '19508' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13003' , name = 'Lake Harmony Rescue Squad Ambulance Corp., Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5707221782' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5707221782' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '105 Lake Dr., P.O. Box 564' , mail_city = 'Lake Harmony' , mail_state = 'PA' , mail_zip_code = '186240564' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13004' , name = 'Lansford Volunteer Ambulance Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706459395' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706459395' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '31 E. Patterson St., P.O. Box 34' , mail_city = 'Lansford' , mail_state = 'PA' , mail_zip_code = '182321504' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39023' , name = 'Lehigh Valley Health Network - MedEvac' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6104028753' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6104028753' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '1200 South Cedar Crest Blvd.' , mail_city = 'Allentown' , mail_state = 'PA' , mail_zip_code = '18103' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13005' , name = 'Lehighton Ambulance Assocaition, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6103775155' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6103775155' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 82' , mail_city = 'Lehighton' , mail_state = 'PA' , mail_zip_code = '182350082' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54010' , name = 'Lost Creek Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5704623743' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5704623743' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 102' , mail_city = 'Lost Creek' , mail_state = 'PA' , mail_zip_code = '17946' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06011' , name = 'Lower Alsace Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107790190' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107790190' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '750 N. 25th Street' , mail_city = 'Reading' , mail_state = 'PA' , mail_zip_code = '19606' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39011' , name = 'Macungie Ambulance Corps.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109662601' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109662601' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 114' , mail_city = 'Macungie' , mail_state = 'PA' , mail_zip_code = '18062' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54011' , name = 'Mahanoy City Emergency Medical Services, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5707732238' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5707732238' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '212 W. Center St.' , mail_city = 'Mahanoy City' , mail_state = 'PA' , mail_zip_code = '179482506' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54009' , name = 'Mahantongo Valley Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706485525' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706485525' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 70' , mail_city = 'Pitman' , mail_state = 'PA' , mail_zip_code = '17964' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13006' , name = 'Mahoning Valley Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5703862518' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5703862518' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '902 Mill Road' , mail_city = 'Lehighton' , mail_state = 'PA' , mail_zip_code = '182359667' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45005' , name = 'Marshalls Creek Fire Company' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5702238445' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5702238445' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 1' , mail_city = 'Marshalls Creek' , mail_state = 'PA' , mail_zip_code = '18335' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54012' , name = 'McAdoo Fire Company, Inc. Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5709292042' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5709292042' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 97' , mail_city = 'McAdoo' , mail_state = 'PA' , mail_zip_code = '18237' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45004' , name = 'Med Mobile EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706565185' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706565185' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '5140 Milford Rd.' , mail_city = 'East Stroudsburg' , mail_state = 'PA' , mail_zip_code = '18302' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48026' , name = 'Metro Ambulance Service, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6105706266' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6105706266' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 680' , mail_city = 'Bethlehem' , mail_state = 'PA' , mail_zip_code = '180160680' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06012' , name = 'Muhlenberg Area Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109295774' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109295774' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 206' , mail_city = 'Temple' , mail_state = 'PA' , mail_zip_code = '195600206' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39015' , name = 'Nationwide Ambulance Services, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '9082761199' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '9082761199' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '409 North Ave. East' , mail_city = 'Cranford' , mail_state = 'NJ' , mail_zip_code = '07016' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48016' , name = 'Nazareth Volunteer Ambulance Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107595422' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107595422' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '49 South Broad Street Rear' , mail_city = 'Nazareth' , mail_state = 'PA' , mail_zip_code = '180640326' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13007' , name = 'Nesquehoning Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706696684' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706696684' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 31' , mail_city = 'Nesquehoning' , mail_state = 'PA' , mail_zip_code = '182400031' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54027' , name = 'New Ringgold Ambulance, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5709432272' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5709432272' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 258' , mail_city = 'New Ringgold' , mail_state = 'PA' , mail_zip_code = '179600258' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48017' , name = 'Northampton Regional Emergency Medical Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102620800' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102620800' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '1525 Canal Street' , mail_city = 'Northampton' , mail_state = 'PA' , mail_zip_code = '18067' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39002' , name = 'Northern Lehigh Ambulance Service, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107697920' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107697920' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 148' , mail_city = 'Slatington' , mail_state = 'PA' , mail_zip_code = '18080' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39012' , name = 'Northern Valley Emergency Medical Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102621075' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102621075' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '2375 Levans Road' , mail_city = 'Coplay' , mail_state = 'PA' , mail_zip_code = '180372202' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39013' , name = 'Northwestern Ambulance Corps, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102982101' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102982101' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '7046 Route 309, PO Box 453' , mail_city = 'New Tripoli' , mail_state = 'PA' , mail_zip_code = '180660453' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54024' , name = 'Nuremberg Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5703843405' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5703843405' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 47' , mail_city = 'Nuremberg' , mail_state = 'PA' , mail_zip_code = '182410047' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06013' , name = 'Oley Fire Company' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109873211' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109873211' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 381' , mail_city = 'Oley' , mail_state = 'PA' , mail_zip_code = '195470381' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54013' , name = 'Orwigsburg Ambulance, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5703662331' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5703662331' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 4' , mail_city = 'Orwigsburg' , mail_state = 'PA' , mail_zip_code = '17961' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13008' , name = 'Palmerton Community Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108267600' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108267600' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 2' , mail_city = 'Palmerton' , mail_state = 'PA' , mail_zip_code = '18071' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13010' , name = 'Penn-Mahoning Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5703862233' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5703862233' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 135' , mail_city = 'Andreas' , mail_state = 'PA' , mail_zip_code = '18211' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54015' , name = 'Pine Grove Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5703453004' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5703453004' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '46 Spruce Street P.O. Box 125' , mail_city = 'Pine Grove' , mail_state = 'PA' , mail_zip_code = '179631715' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48018' , name = 'Plainfield Township VFC Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108633302' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108633302' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '6480 Sullivan Trail, P.O. Box 568' , mail_city = 'Wind Gap' , mail_state = 'PA' , mail_zip_code = '18091' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45013' , name = 'Pocono Area Ambulance Services Ltd' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708516012' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708516012' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '330 Lake of the Pines' , mail_city = 'East Stroudsburg' , mail_state = 'PA' , mail_zip_code = '18302' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45011' , name = 'Pocono Mountain Regional Emergency Medical Service' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708398485' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708398485' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 580' , mail_city = 'Poc. Summit' , mail_state = 'PA' , mail_zip_code = '18346' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54023' , name = 'Pottsville/Schuylkill Haven Area EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706229647' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706229647' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '320 N. Ninth Street' , mail_city = 'Pottsville' , mail_state = 'PA' , mail_zip_code = '17901' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 13) , affiliate_num = '13002' , name = 'Regional EMS & Critical Care, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6103779027' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6103779027' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 191' , mail_city = 'Lehighton' , mail_state = 'PA' , mail_zip_code = '182350191' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45006' , name = 'Response Event Services LLC' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6105598606' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6105598606' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '8 Middle Court' , mail_city = 'Easton' , mail_state = 'PA' , mail_zip_code = '180450000' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54016' , name = 'Ringtown Community Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708895757' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708895757' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 339' , mail_city = 'Ringtown' , mail_state = 'PA' , mail_zip_code = '17967' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54026' , name = 'Ryan Township Emergency and Rescue Squad, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5704673424' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5704673424' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 202' , mail_city = 'Barnesville' , mail_state = 'PA' , mail_zip_code = '18214' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54017' , name = 'Saint Clair Veterans Memorial Ambulance Fund' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5704297020' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5704297020' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 124' , mail_city = 'Saint Clair' , mail_state = 'PA' , mail_zip_code = '17970' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06403' , name = 'Schuylkill Valley EMS' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109263858' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109263858' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 625' , mail_city = 'Leesport' , mail_state = 'PA' , mail_zip_code = '195330625' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06019' , name = 'Select Ambulance, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '2678089854' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '2678089854' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '328 Tulpehocken Avenue' , mail_city = 'West Reading' , mail_state = 'pa' , mail_zip_code = '196111452' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54014' , name = 'Shenandoah Community Ambulance Association' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5704620500' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5704620500' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '220 N. White Street' , mail_city = 'Shenandoah' , mail_state = 'PA' , mail_zip_code = '17976' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06402' , name = 'Southern Berks Regional Emergency Medical Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6107751041' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6107751041' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '769 Mountain View Rd.' , mail_city = 'Reading' , mail_state = 'PA' , mail_zip_code = '19607' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48020' , name = 'Suburban Emergency Medical Services' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6109237500' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6109237500' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 3339' , mail_city = 'Palmer' , mail_state = 'PA' , mail_zip_code = '180433339' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54025' , name = 'Tamaqua Community Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706683342' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706683342' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '98 N. Railroad Street' , mail_city = 'Tamaqua' , mail_state = 'PA' , mail_zip_code = '18252' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45010' , name = 'Tobyhanna Army Depot' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708957300' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708957300' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '11 Hap Arnold Boulevard' , mail_city = 'Tobyhanna' , mail_state = 'PA' , mail_zip_code = '184665056' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06017' , name = 'Topton American Legion Community Ambulance Service' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106824333' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106824333' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 22' , mail_city = 'Topton' , mail_state = 'PA' , mail_zip_code = '195621002' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54003' , name = 'Tower-Porter Community Ambulance Service Club' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '7176472271' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '7176472271' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 33' , mail_city = 'Tower City' , mail_state = 'PA' , mail_zip_code = '179800033' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54020' , name = 'Tremont Area Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706952500' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706952500' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '49 North Street' , mail_city = 'Tremont' , mail_state = 'PA' , mail_zip_code = '17981' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54203' , name = 'Tremont Transport Service' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706952500' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706952500' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '49 North Street' , mail_city = 'Tremont' , mail_state = 'PA' , mail_zip_code = '179811526' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 39) , affiliate_num = '39017' , name = 'Upper Saucon Ambulance Corps' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6102821565' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6102821565' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '5560 Camp Meeting Road' , mail_city = 'Center Valley' , mail_state = 'PA' , mail_zip_code = '18034' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54022' , name = 'Washington Fire Company Community Ambulance Assoc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5708752200' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5708752200' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 121' , mail_city = 'Ashland' , mail_state = 'PA' , mail_zip_code = '17921' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 45) , affiliate_num = '45007' , name = 'West End Community Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106815810' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106815810' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 200' , mail_city = 'Effort' , mail_state = 'PA' , mail_zip_code = '183300200' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 54) , affiliate_num = '54402' , name = 'West Schuylkill Advanced Life Support' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '5706953575' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '5706953575' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '49 North Street' , mail_city = 'Tremont' , mail_state = 'PA' , mail_zip_code = '179811526' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 6) , affiliate_num = '06018' , name = 'Western Berks Ambulance Association, Inc.' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6106781545' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6106781545' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = 'P.O. Box 2506' , mail_city = 'West Lawn' , mail_state = 'PA' , mail_zip_code = '19609' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
insert service set county_code = (select code from county_code_name_map where emsrs_code = 48) , affiliate_num = '48022' , name = 'Wind Gap Ambulance' , charter_kind = '9' , corpadmin_contact_name ='' , corpadmin_primary_phone_num = '6108637623' , be_emsof_participant = FALSE , coo_name = '' , coo_work_phone_num = '6108637623' , physical_street_address_line_1 = '' , physical_city = '' , physical_state = '' , physical_zip_code = '' , mail_address_line_1 = '433 North Broadway' , mail_city = 'Wind Gap' , mail_state = 'PA' , mail_zip_code = '18091' , num_doh_licensed_vehicles = 0 , num_ambulances = 0 , be_qrs_unrecognized = FALSE , be_rescue_unrecognized = FALSE; insert service_user set password_reset_email_address = '';
;
update ignore service set short_name = SUBSTRING_INDEX(name,' ',1) -- DANGER!!!  RESETS ALL PRE-EXISTING SERVICE NAMES IN TABLE!!!
;
update ignore service set short_name = 'Bethlehem Twp' where name = 'Bethlehem Township Volunteer Fire Company'
;
update ignore service set short_name = 'Bushkill Twp' where name = 'Bushkill Township Volunteer Ambulance Corps'
;
update ignore service set short_name = 'Reading' where name = 'City of Reading Emergency Medical Services'
;
update ignore service set short_name = 'L & P' where name = 'L & P Care Ambulance'
;
update ignore service set short_name = 'Lower Alsace' where name = 'Lower Alsace Ambulance'
;
update ignore service set short_name = 'Western Berks' where name = 'Western Berks Ambulance Association, Inc.'
;
update ignore service set short_name = 'Southern Berks' where name = 'Southern Berks Regional Emergency Medical Services'
;
update ignore service set short_name = 'Lake Harmony' where name = 'Lake Harmony Rescue Squad Ambulance Corp., Inc.'
;
update ignore service set short_name = 'Greater Weatherly' where name = 'Greater Weatherly Ambulance Association, Inc.'
;
update ignore service set short_name = 'Northern Lehigh' where name = 'Northern Lehigh Ambulance Service, Inc.'
;
update ignore service set short_name = 'Allentown' where name = 'City of Allentown EMS'
;
update ignore service set short_name = 'Whitehall' where name = 'Interstate Nursing Services Inc. DBA: Whitehall Medical Transport Services'
;
update ignore service set short_name = 'NOVA' where name = 'Northern Valley Emergency Medical Services'
;
update ignore service set short_name = 'Upper Saucon' where name = 'Upper Saucon Ambulance Corps'
;
update ignore service set short_name = 'LVHN MedEvac' where name = 'Lehigh Valley Health Network - MedEvac'
;
update ignore service set short_name = 'Central Pocono' where name = 'Central Pocono Ambulance Association, Inc.'
;
update ignore service set short_name = 'Med Mobile' where name = 'Med Mobile EMS'
;
update ignore service set short_name = 'Marshalls Creek' where name = 'Marshalls Creek Fire Company'
;
update ignore service set short_name = 'West End' where name = 'West End Community Ambulance '
;
update ignore service set short_name = 'PMR' where name = 'Pocono Mountain Regional Emergency Medical Service'
;
update ignore service set short_name = 'Pocono Area' where name = 'Pocono Area Ambulance Services Ltd'
;
update ignore service set short_name = 'Bethlehem' where name = 'City of Bethlehem EMS'
;
update ignore service set short_name = 'Wind Gap' where name = 'Wind Gap Ambulance'
;
update ignore service set short_name = 'Lifestar Response' where name = 'Falck EMS DBA: Lifestar Response of New Jersey'
;
update ignore service set short_name = 'Eagle' where name = 'Hospital Ambulance LLC dba: Eagle Medical Transport'
;
update ignore service set short_name = 'East Allen' where name = 'East Allen Township Volunteer Ambulance Corps'
;
update ignore service set short_name = 'Minersville' where name = 'Good Will Fire Company #1 DBA: Minersville EMS'
;
update ignore service set short_name = 'Lost Creek' where name = 'Lost Creek Community Ambulance Association'
;
update ignore service set short_name = 'Pine Grove' where name = 'Pine Grove Community Ambulance Association'
;
update ignore service set short_name = 'Saint Clair' where name = 'Saint Clair Veterans Memorial Ambulance Fund'
;
update ignore service set short_name = 'Pottsville' where name = 'Pottsville/Schuylkill Haven Area EMS'
;
update ignore service set short_name = 'New Ringgold' where name = 'New Ringgold Ambulance, Inc.'
;
update ignore service set short_name = 'West Schuylkill' where name = 'West Schuylkill Advanced Life Support'
;
update ignore service set short_name = 'WCARA' where name = 'Westmoreland County Ambulance And Rescue Association'
;
update ignore service set short_name = 'NWAC' where name = 'Northwestern Ambulance Corps, Inc.'
;
update ignore service set short_name = 'Hanover Twp' where name = 'Hanover Township Volunteer Fire Company #1'
;
update ignore service set short_name = 'Washington FCCA' where name = 'Washington Fire Company Community Ambulance Assoc.'
;
update ignore service set short_name = 'Tremont Transport' where name = 'Tremont Transport Service'
;
SET FOREIGN_KEY_CHECKS=1
;
COMMIT