START TRANSACTION
;
update service set short_name = '7th Ward' where id = '354';
update service set short_name = 'A Vital Response' where id = '355';
update service set short_name = 'A-Med' where id = '356';
update service set short_name = 'AAA' where id = '357';
update service set short_name = 'Able' where id = '358';
update service set short_name = 'Ace Care' where id = '359';
update service set short_name = 'ACEMS' where id = '184';
update service set short_name = 'Acute Care DBA Acute Care Med' where id = '360';
update service set short_name = 'Adams' where id = '307';
update service set short_name = 'Adamsburg' where id = '123';
update service set short_name = 'Advance Care' where id = '361';
update service set short_name = 'Advanced Nurse Transport' where id = '363';
update service set short_name = 'Advantage Ambulance' where id = '364';
update service set short_name = 'Advantage Medical Transport' where id = '365';
update service set short_name = 'AF Dobler' where id = '366';
update service set short_name = 'Air Methods Maryland' where id = '369';
update service set short_name = 'Albion' where id = '372';
update service set short_name = 'Allegheny Co Airport' where id = '283';
update service set short_name = 'Allegheny Mountains Rescue' where id = '285';
update service set short_name = 'Allentown' where id = '198';
update service set short_name = 'Alliance' where id = '373';
update service set short_name = 'Alpha' where id = '374';
update service set short_name = 'Altoona Logan' where id = '375';
update service set short_name = 'Ambu Quest' where id = '376';
update service set short_name = 'Ambulance & Chair' where id = '92';
update service set short_name = 'Ambulance of America' where id = '379';
update service set short_name = 'Ambulimo' where id = '378';
update service set short_name = 'AMERI MEX' where id = '381';
update service set short_name = 'American Health' where id = '383';
update service set short_name = 'American Life' where id = '384';
update service set short_name = 'American Patient' where id = '386';
update service set short_name = 'American Patriot' where id = '387';
update service set short_name = 'Americas LifeLine' where id = '388';
update service set short_name = 'Americus' where id = '389';
update service set short_name = 'Ameriquest' where id = '390';
update service set short_name = 'AMEX' where id = '362';
update service set short_name = 'AMR' where id = '385';
update service set short_name = 'Andina Care' where id = '391';
update service set short_name = 'ArcelorMittal' where id = '392';
update service set short_name = 'ArcelorMittal Steelton' where id = '393';
update service set short_name = 'Archbald' where id = '394';
update service set short_name = 'AREA' where id = '395';
update service set short_name = 'Arnold' where id = '105';
update service set short_name = 'Arrow' where id = '397';
update service set short_name = 'Art of Life' where id = '398';
update service set short_name = 'ASA' where id = '380';
update service set short_name = 'Ashley' where id = '399';
update service set short_name = 'Aston-Beechwood' where id = '400';
update service set short_name = 'Atlantic' where id = '401';
update service set short_name = 'Auburn' where id = '187';
update service set short_name = 'Austin' where id = '347';
update service set short_name = 'Avella' where id = '152';
update service set short_name = 'Avoca' where id = '402';
update service set short_name = 'Avondale' where id = '403';
update service set short_name = 'Avonmore' where id = '103';
update service set short_name = 'Back Mountain' where id = '404';
update service set short_name = 'Baldwin' where id = '25';
update service set short_name = 'Bally' where id = '188';
update service set short_name = 'Barnes Kasson' where id = '405';
update service set short_name = 'Bath' where id = '189';
update service set short_name = 'BATS' where id = '340';
update service set short_name = 'Bear Creek – Buck' where id = '406';
update service set short_name = 'Beaver Springs' where id = '407';
update service set short_name = 'Bedford' where id = '408';
update service set short_name = 'Beech Creek – Blanchard' where id = '409';
update service set short_name = 'Belle Vernon' where id = '287';
update service set short_name = 'Bellefonte' where id = '410';
update service set short_name = 'Bellevue' where id = '278';
update service set short_name = 'BelMed' where id = '411';
update service set short_name = 'Bennetts Valley' where id = '326';
update service set short_name = 'Bensalem' where id = '413';
update service set short_name = 'Bentleyville' where id = '161';
update service set short_name = 'Benton' where id = '414';
update service set short_name = 'Bentworth' where id = '150';
update service set short_name = 'Berkeley' where id = '39';
update service set short_name = 'Berlin' where id = '415';
update service set short_name = 'Berwick' where id = '416';
update service set short_name = 'Berwyn' where id = '417';
update service set short_name = 'Best Response' where id = '418';
update service set short_name = 'Bethel' where id = '190';
update service set short_name = 'Bethlehem EMS' where id = '199';
update service set short_name = 'Bethlehem VFC' where id = '191';
update service set short_name = 'Big Knob' where id = '145';
update service set short_name = 'Big Valley' where id = '419';
update service set short_name = 'Biglerville' where id = '420';
update service set short_name = 'Blacklick Valley' where id = '421';
update service set short_name = 'Blain' where id = '422';
update service set short_name = 'Blaine Hille' where id = '279';
update service set short_name = 'Blakely' where id = '423';
update service set short_name = 'Blandon' where id = '192';
update service set short_name = 'Blawnox-Glenover' where id = '308';
update service set short_name = 'Bloomfield' where id = '424';
update service set short_name = 'Bloomsburg' where id = '425';
update service set short_name = 'Blossburg' where id = '426';
update service set short_name = 'Blue Ridge Mountain' where id = '428';
update service set short_name = 'Bobtown' where id = '147';
update service set short_name = 'Boeing' where id = '429';
update service set short_name = 'Boothwyn' where id = '430';
update service set short_name = 'Boswell' where id = '431';
update service set short_name = 'Boyertown' where id = '193';
update service set short_name = 'Bradford Fire' where id = '338';
update service set short_name = 'Brady' where id = '318';
update service set short_name = 'Brandywine' where id = '432';
update service set short_name = 'Bravo' where id = '427';
update service set short_name = 'Brentwood' where id = '26';
update service set short_name = 'Brickerville' where id = '433';
update service set short_name = 'Bridgeville' where id = '303';
update service set short_name = 'Brighton' where id = '144';
update service set short_name = 'Brockway' where id = '333';
update service set short_name = 'Brogue' where id = '434';
update service set short_name = 'Brookhaven' where id = '435';
update service set short_name = 'Brookside' where id = '436';
update service set short_name = 'Brownsville' where id = '69';
update service set short_name = 'Bryn Athyn' where id = '437';
update service set short_name = 'Bucks Co' where id = '438';
update service set short_name = 'Bucks Mont' where id = '439';
update service set short_name = 'Bucktail' where id = '440';
update service set short_name = 'Buffalo' where id = '62';
update service set short_name = 'Burholme' where id = '441';
update service set short_name = 'Bushkill EC' where id = '194';
update service set short_name = 'Bushkill Twp' where id = '195';
update service set short_name = 'Butler Ambulance' where id = '54';
update service set short_name = 'Butler Fire' where id = '130';
update service set short_name = 'Butler Medical Transport' where id = '442';
update service set short_name = 'C & D' where id = '443';
update service set short_name = 'Callery' where id = '66';
update service set short_name = 'Cambria' where id = '444';
update service set short_name = 'Cambridge' where id = '445';
update service set short_name = 'Cameron' where id = '316';
update service set short_name = 'Camp Hill' where id = '446';
update service set short_name = 'Canadochly Valley' where id = '447';
update service set short_name = 'Canonsburg' where id = '134';
update service set short_name = 'Capital Care' where id = '448';
update service set short_name = 'Capital Health' where id = '449';
update service set short_name = 'Care 1 EMS' where id = '554';
update service set short_name = 'CareOne Amb' where id = '450';
update service set short_name = 'Caring Hearts' where id = '451';
update service set short_name = 'Carnegie' where id = '2';
update service set short_name = 'Cecil/Muse' where id = '102';
update service set short_name = 'Center' where id = '300';
update service set short_name = 'Centerville' where id = '452';
update service set short_name = 'Central Bucks' where id = '453';
update service set short_name = 'Central Erie' where id = '454';
update service set short_name = 'Central Juniata' where id = '455';
update service set short_name = 'Central Medical' where id = '456';
update service set short_name = 'Central Pocono' where id = '196';
update service set short_name = 'Centre LifeLink' where id = '457';
update service set short_name = 'Century' where id = '458';
update service set short_name = 'Cetronia' where id = '197';
update service set short_name = 'Chal-Brit' where id = '459';
update service set short_name = 'Chambersburg' where id = '460';
update service set short_name = 'Charleroi' where id = '288';
update service set short_name = 'Cheltenham' where id = '462';
update service set short_name = 'Cherryhill' where id = '286';
update service set short_name = 'Chester Co M91' where id = '872';
update service set short_name = 'Chestnut Ridge' where id = '463';
update service set short_name = 'Chicora' where id = '55';
update service set short_name = 'Chinchilla' where id = '464';
update service set short_name = 'Chippewa' where id = '143';
update service set short_name = 'Christiana CAA' where id = '465';
update service set short_name = 'Christiana Care LifeNet' where id = '371';
update service set short_name = 'Citizen Care' where id = '845';
update service set short_name = 'Citizens Ambulance' where id = '82';
update service set short_name = 'Citizens HC1' where id = '466';
update service set short_name = 'Citizens VFC' where id = '467';
update service set short_name = 'Citizens VHC' where id = '182';
update service set short_name = 'CKHS' where id = '505';
update service set short_name = 'Clairton' where id = '4';
update service set short_name = 'Clarendon' where id = '470';
update service set short_name = 'Clarion Hospital' where id = '471';
update service set short_name = 'Clarion Medical' where id = '472';
update service set short_name = 'Clarks Summit' where id = '473';
update service set short_name = 'clarksville' where id = '34';
update service set short_name = 'CLAYSVILLE' where id = '93';
update service set short_name = 'Clearfield' where id = '319';
update service set short_name = 'Clifford' where id = '474';
update service set short_name = 'Clifton Heights' where id = '475';
update service set short_name = 'Clinton' where id = '476';
update service set short_name = 'CMU' where id = '304';
update service set short_name = 'Cochranton' where id = '477';
update service set short_name = 'Collingdale' where id = '478';
update service set short_name = 'Columbia' where id = '479';
update service set short_name = 'Commonwealth' where id = '480';
update service set short_name = 'Community Amb Assn' where id = '481';
update service set short_name = 'Community Amb Svc' where id = '482';
update service set short_name = 'Community Life Team' where id = '484';
update service set short_name = 'Community LSS' where id = '483';
update service set short_name = 'Compassionate' where id = '485';
update service set short_name = 'Concordville' where id = '486';
update service set short_name = 'Conemaugh DART' where id = '487';
update service set short_name = 'Conemaugh MedStar' where id = '488';
update service set short_name = 'Conemaugh Twp' where id = '489';
update service set short_name = 'Conemaugh Valley' where id = '490';
update service set short_name = 'Conemaugh VFC' where id = '491';
update service set short_name = 'Conestoga' where id = '492';
update service set short_name = 'Confluence' where id = '493';
update service set short_name = 'Conneaut Lake' where id = '494';
update service set short_name = 'Coopersburg' where id = '201';
update service set short_name = 'Cornerstone' where id = '496';
update service set short_name = 'Cornplanter' where id = '497';
update service set short_name = 'Corry' where id = '498';
update service set short_name = 'Cottage Amb' where id = '499';
update service set short_name = 'Cottage Hose' where id = '500';
update service set short_name = 'Coudersport' where id = '349';
update service set short_name = 'Covington' where id = '501';
update service set short_name = 'Crabtree' where id = '124';
update service set short_name = 'Crafton' where id = '141';
update service set short_name = 'Cranesville' where id = '502';
update service set short_name = 'Crescent' where id = '503';
update service set short_name = 'Crozer EMS' where id = '504';
update service set short_name = 'CTEMS' where id = '56';
update service set short_name = 'Cumberland Goodwill' where id = '506';
update service set short_name = 'Cumberland Valley' where id = '507';
update service set short_name = 'Cure' where id = '508';
update service set short_name = 'Dalton' where id = '510';
update service set short_name = 'Damascus' where id = '511';
update service set short_name = 'Danville' where id = '512';
update service set short_name = 'Darby' where id = '513';
update service set short_name = 'Dauntless' where id = '514';
update service set short_name = 'Delaware' where id = '515';
update service set short_name = 'Delco' where id = '516';
update service set short_name = 'Dewey' where id = '202';
update service set short_name = 'Diamond Care' where id = '518';
update service set short_name = 'Dickson' where id = '519';
update service set short_name = 'Dingman' where id = '520';
update service set short_name = 'Distant Area' where id = '46';
update service set short_name = 'DLA' where id = '577';
update service set short_name = 'Dorrance' where id = '521';
update service set short_name = 'Dover Area ALS' where id = '522';
update service set short_name = 'Dover Area Amb' where id = '523';
update service set short_name = 'Dublin' where id = '524';
update service set short_name = 'DuBois' where id = '328';
update service set short_name = 'DuBoistown' where id = '525';
update service set short_name = 'Duncannon' where id = '526';
update service set short_name = 'Duncansville' where id = '527';
update service set short_name = 'Duquesne' where id = '5';
update service set short_name = 'DuSan' where id = '325';
update service set short_name = 'Dushore' where id = '528';
update service set short_name = 'Dynamic' where id = '529';
update service set short_name = 'Eagle' where id = '218';
update service set short_name = 'Eagles Mere' where id = '530';
update service set short_name = 'EAPS' where id = '21';
update service set short_name = 'East Allen' where id = '203';
update service set short_name = 'East Brady' where id = '531';
update service set short_name = 'East Butler' where id = '57';
update service set short_name = 'East Carnegie' where id = '289';
update service set short_name = 'East Deer' where id = '160';
update service set short_name = 'East Hills' where id = '532';
update service set short_name = 'East Lansdowne' where id = '533';
update service set short_name = 'East Pennsboro' where id = '534';
update service set short_name = 'East Whiteland' where id = '535';
update service set short_name = 'Eastern Regional' where id = '536';
update service set short_name = 'EasternCare' where id = '833';
update service set short_name = 'Easton' where id = '204';
update service set short_name = 'Ebensburg' where id = '537';
update service set short_name = 'Economy' where id = '48';
update service set short_name = 'Eddystone' where id = '538';
update service set short_name = 'Edgewood' where id = '314';
update service set short_name = 'Edinboro' where id = '539';
update service set short_name = 'Edwardsville' where id = '540';
update service set short_name = 'Einstein' where id = '541';
update service set short_name = 'Eldred Boro' where id = '339';
update service set short_name = 'Eldred Twp' where id = '542';
update service set short_name = 'Eldredsville' where id = '543';
update service set short_name = 'Elgin-Beaverdam' where id = '544';
update service set short_name = 'Elite EMS' where id = '545';
update service set short_name = 'Elite Medical Team' where id = '546';
update service set short_name = 'Elite Medical Transport' where id = '547';
update service set short_name = 'Elizabeth Fire' where id = '41';
update service set short_name = 'Elizabeth Twp' where id = '31';
update service set short_name = 'Ellsworth' where id = '155';
update service set short_name = 'Elverson' where id = '548';
update service set short_name = 'Elysburg' where id = '549';
update service set short_name = 'EmergyCare' where id = '551';
update service set short_name = 'Eminent' where id = '552';
update service set short_name = 'Emlenton' where id = '553';
update service set short_name = 'Emmaus' where id = '205';
update service set short_name = 'EMS Southwest' where id = '80';
update service set short_name = 'EMSI/Region 4' where id = '183';
update service set short_name = 'Emstat' where id = '556';
update service set short_name = 'EMTS' where id = '557';
update service set short_name = 'Enon Valley' where id = '85';
update service set short_name = 'Ephrata' where id = '558';
update service set short_name = 'Erway' where id = '559';
update service set short_name = 'ETA JEFFSTAT' where id = '550';
update service set short_name = 'Etna' where id = '164';
update service set short_name = 'Eureka CAS' where id = '157';
update service set short_name = 'Eureka VFC' where id = '560';
update service set short_name = 'Evangelical' where id = '561';
update service set short_name = 'Evans City' where id = '154';
update service set short_name = 'Event MSS' where id = '562';
update service set short_name = 'Everest' where id = '563';
update service set short_name = 'Exeter AA' where id = '206';
update service set short_name = 'Exeter CAA' where id = '564';
update service set short_name = 'Express' where id = '565';
update service set short_name = 'Factoryville' where id = '566';
update service set short_name = 'Fairchance' where id = '176';
update service set short_name = 'Fairfield CFC' where id = '567';
update service set short_name = 'Fairfield Hose' where id = '568';
update service set short_name = 'Fairmount' where id = '569';
update service set short_name = 'Fairview Fire' where id = '570';
update service set short_name = 'Fairview Twp' where id = '571';
update service set short_name = 'Fallowfield' where id = '100';
update service set short_name = 'Fame' where id = '572';
update service set short_name = 'Family' where id = '573';
update service set short_name = 'Fannett-Metal' where id = '574';
update service set short_name = 'FAST' where id = '579';
update service set short_name = 'Fayette' where id = '73';
update service set short_name = 'Fayette Twp' where id = '575';
update service set short_name = 'Fayetteville' where id = '576';
update service set short_name = 'FDNV' where id = '19';
update service set short_name = 'Fellows' where id = '578';
update service set short_name = 'First Priority' where id = '581';
update service set short_name = 'First Ward' where id = '582';
update service set short_name = 'Five Star' where id = '583';
update service set short_name = 'Fivepointville' where id = '584';
update service set short_name = 'Fleetwood' where id = '208';
update service set short_name = 'Folcroft' where id = '585';
update service set short_name = 'Forbes Road' where id = '177';
update service set short_name = 'Ford City' where id = '43';
update service set short_name = 'Forest City' where id = '586';
update service set short_name = 'Forest Hills' where id = '587';
update service set short_name = 'Fort Allen' where id = '309';
update service set short_name = 'Fort Cherry' where id = '133';
update service set short_name = 'Fox' where id = '329';
update service set short_name = 'Foxwall' where id = '8';
update service set short_name = 'Frackville' where id = '209';
update service set short_name = 'Franklin Twp' where id = '588';
update service set short_name = 'Franklin-Northmoreland' where id = '589';
update service set short_name = 'Freeland-Northside' where id = '590';
update service set short_name = 'Freeport' where id = '44';
update service set short_name = 'Friendly' where id = '555';
update service set short_name = 'Friendship Amb' where id = '591';
update service set short_name = 'Friendship Hose' where id = '592';
update service set short_name = 'FWM' where id = '593';
update service set short_name = 'Gale' where id = '594';
update service set short_name = 'Geisinger' where id = '596';
update service set short_name = 'Gem' where id = '597';
update service set short_name = 'Genesee' where id = '350';
update service set short_name = 'Genesis' where id = '598';
update service set short_name = 'Gettysburg Fire' where id = '600';
update service set short_name = 'Gettysburg Hospital' where id = '601';
update service set short_name = 'Gilbertsville' where id = '602';
update service set short_name = 'Girardville' where id = '210';
update service set short_name = 'Glen Rock' where id = '603';
update service set short_name = 'Glendale' where id = '282';
update service set short_name = 'Glenville' where id = '604';
update service set short_name = 'Global MTA' where id = '605';
update service set short_name = 'Global MTS' where id = '211';
update service set short_name = 'Goldsboro' where id = '606';
update service set short_name = 'Good Choice' where id = '607';
update service set short_name = 'Good Fellowship' where id = '608';
update service set short_name = 'Goodwill FC' where id = '609';
update service set short_name = 'Goodwill HC' where id = '610';
update service set short_name = 'Gordonville' where id = '611';
update service set short_name = 'Goshen' where id = '612';
update service set short_name = 'Gouldsboro' where id = '613';
update service set short_name = 'Grand Valley' where id = '614';
update service set short_name = 'Grand View' where id = '615';
update service set short_name = 'Grantley' where id = '616';
update service set short_name = 'Great Bend-Hallstead' where id = '617';
update service set short_name = 'Greater Columbia' where id = '618';
update service set short_name = 'Greater Pittston' where id = '619';
update service set short_name = 'Greater Valley' where id = '620';
update service set short_name = 'Greater Weatherly' where id = '213';
update service set short_name = 'Greenfield Erie' where id = '621';
update service set short_name = 'Greenfield Lackawanna' where id = '622';
update service set short_name = 'Greensboro Mon Twp' where id = '79';
update service set short_name = 'Greenwood Village' where id = '67';
update service set short_name = 'Guardian Angel' where id = '36';
update service set short_name = 'Guardian Angels' where id = '623';
update service set short_name = 'Gulfstream' where id = '624';
update service set short_name = 'Guthrie Air' where id = '367';
update service set short_name = 'Halifax' where id = '625';
update service set short_name = 'Hamburg' where id = '214';
update service set short_name = 'Hamlin' where id = '626';
update service set short_name = 'Hampden' where id = '627';
update service set short_name = 'Hampton' where id = '9';
update service set short_name = 'Hanover Ambulance' where id = '49';
update service set short_name = 'Hanover Hospital' where id = '628';
update service set short_name = 'Hanover QRS' where id = '95';
update service set short_name = 'Hanover Twp CAA' where id = '629';
update service set short_name = 'Hanover Twp VFC' where id = '215';
update service set short_name = 'Harborcreek' where id = '630';
update service set short_name = 'Harding-Mt Zion' where id = '631';
update service set short_name = 'Harford' where id = '632';
update service set short_name = 'Harleysville' where id = '633';
update service set short_name = 'Harmony' where id = '58';
update service set short_name = 'Harveys Lake' where id = '634';
update service set short_name = 'Hastings' where id = '635';
update service set short_name = 'Hawley' where id = '636';
update service set short_name = 'Hayatt' where id = '637';
update service set short_name = 'Health Ride Plus' where id = '639';
update service set short_name = 'Health Trans' where id = '763';
update service set short_name = 'HealthFleet' where id = '640';
update service set short_name = 'Heart to Heart' where id = '641';
update service set short_name = 'Hecktown' where id = '216';
update service set short_name = 'Hegins' where id = '217';
update service set short_name = 'Heidelberg' where id = '181';
update service set short_name = 'Hemlock Farms' where id = '642';
update service set short_name = 'Hepburn' where id = '643';
update service set short_name = 'Hersheypark' where id = '644';
update service set short_name = 'Hickory [109]' where id = '149';
update service set short_name = 'Hickory [110]' where id = '88';
update service set short_name = 'Hiller' where id = '168';
update service set short_name = 'Hillsgrove' where id = '645';
update service set short_name = 'Hobbie' where id = '646';
update service set short_name = 'Holiday Park' where id = '38';
update service set short_name = 'Hollidaysburg' where id = '647';
update service set short_name = 'Holmes' where id = '648';
update service set short_name = 'Holy Spirit' where id = '649';
update service set short_name = 'Homer City' where id = '295';
update service set short_name = 'Hookstown' where id = '179';
update service set short_name = 'Hope' where id = '650';
update service set short_name = 'HOPS' where id = '651';
update service set short_name = 'Horsham' where id = '652';
update service set short_name = 'Houtzdale-Ramey' where id = '327';
update service set short_name = 'Hughestown' where id = '653';
update service set short_name = 'Hughesville' where id = '654';
update service set short_name = 'Hunlock Creek' where id = '655';
update service set short_name = 'Huntingdon' where id = '656';
update service set short_name = 'Huntington Valley' where id = '657';
update service set short_name = 'Hustontown' where id = '658';
update service set short_name = 'Hyndman' where id = '659';
update service set short_name = 'Independence' where id = '47';
update service set short_name = 'Ingram' where id = '10';
update service set short_name = 'Inspire' where id = '660';
update service set short_name = 'Instant Response' where id = '661';
update service set short_name = 'Irvona' where id = '321';
update service set short_name = 'Irwin' where id = '106';
update service set short_name = 'Jackson Fire' where id = '662';
update service set short_name = 'Jackson Vol Amb' where id = '663';
update service set short_name = 'Jacobus Lions' where id = '664';
update service set short_name = 'Jamestown' where id = '665';
update service set short_name = 'Jeannette' where id = '107';
update service set short_name = 'Jefferson Ambulance' where id = '76';
update service set short_name = 'Jefferson County' where id = '334';
update service set short_name = 'Jefferson Hills' where id = '11';
update service set short_name = 'Jefferson QRS' where id = '180';
update service set short_name = 'Jefferson Twp Amb' where id = '666';
update service set short_name = 'Jefferson Twp Fire' where id = '96';
update service set short_name = 'JeffSTAT' where id = '370';
update service set short_name = 'Jenkins' where id = '667';
update service set short_name = 'Jennerstown' where id = '668';
update service set short_name = 'Jersey Shore' where id = '669';
update service set short_name = 'Jessup' where id = '670';
update service set short_name = 'JET' where id = '671';
update service set short_name = 'John Carroll' where id = '672';
update service set short_name = 'Johnstown' where id = '673';
update service set short_name = 'Juniata Valley' where id = '674';
update service set short_name = 'Justus' where id = '675';
update service set short_name = 'Karthaus' where id = '322';
update service set short_name = 'Kecksburg' where id = '108';
update service set short_name = 'KENNEDY TWP' where id = '305';
update service set short_name = 'Kennett' where id = '676';
update service set short_name = 'Kettle Creek' where id = '351';
update service set short_name = 'Keystone MR' where id = '677';
update service set short_name = 'Keystone QT' where id = '678';
update service set short_name = 'Keystone Valley' where id = '679';
update service set short_name = 'Kingston' where id = '680';
update service set short_name = 'Kirwan Heights' where id = '12';
update service set short_name = 'Kittanning' where id = '45';
update service set short_name = 'Klecknersville' where id = '220';
update service set short_name = 'Knox' where id = '681';
update service set short_name = 'Kuhl' where id = '682';
update service set short_name = 'Kunkle' where id = '683';
update service set short_name = 'Kutztown' where id = '221';
update service set short_name = 'L & P' where id = '222';
update service set short_name = 'Lack Tuscarora' where id = '684';
update service set short_name = 'Lackawaxen' where id = '685';
update service set short_name = 'Lafayette' where id = '686';
update service set short_name = 'Lairdsville' where id = '687';
update service set short_name = 'Lake City' where id = '688';
update service set short_name = 'Lake Harmony' where id = '223';
update service set short_name = 'Lake Meade' where id = '689';
update service set short_name = 'Lake Shore' where id = '690';
update service set short_name = 'Lake Silkworth' where id = '691';
update service set short_name = 'Lake Winola' where id = '692';
update service set short_name = 'Lambertville-New Hope' where id = '693';
update service set short_name = 'Lancaster' where id = '694';
update service set short_name = 'Landisburg' where id = '695';
update service set short_name = 'Lansdowne' where id = '696';
update service set short_name = 'Lansford' where id = '224';
update service set short_name = 'Laporte' where id = '697';
update service set short_name = 'Larksville' where id = '698';
update service set short_name = 'Latrobe' where id = '172';
update service set short_name = 'Laurel Valley' where id = '120';
update service set short_name = 'Lawn' where id = '699';
update service set short_name = 'Lawrence Park' where id = '700';
update service set short_name = 'Lawrenceville' where id = '701';
update service set short_name = 'Leader' where id = '702';
update service set short_name = 'Lebanon' where id = '580';
update service set short_name = 'Leedom' where id = '703';
update service set short_name = 'Legend' where id = '495';
update service set short_name = 'Lehighton' where id = '226';
update service set short_name = 'Leola' where id = '704';
update service set short_name = 'Letterkenny' where id = '705';
update service set short_name = 'Levittown-Fairless Hills' where id = '707';
update service set short_name = 'Liberty' where id = '708';
update service set short_name = 'Life Alert' where id = '709';
update service set short_name = 'Life Alliance' where id = '710';
update service set short_name = 'Life Flight' where id = '595';
update service set short_name = 'Life Line' where id = '509';
update service set short_name = 'Life Lion CCT' where id = '711';
update service set short_name = 'Life Lion EMS' where id = '712';
update service set short_name = 'Life Med' where id = '960';
update service set short_name = 'Life Net of New York' where id = '368';
update service set short_name = 'Life Rescue' where id = '713';
update service set short_name = 'Lifecross' where id = '714';
update service set short_name = 'LifeForce' where id = '715';
update service set short_name = 'LifeLine' where id = '716';
update service set short_name = 'LifeNet Amb' where id = '717';
update service set short_name = 'Lifestar Amb' where id = '718';
update service set short_name = 'Lifestar Response' where id = '207';
update service set short_name = 'Lifestat' where id = '83';
update service set short_name = 'Ligonier Valley' where id = '119';
update service set short_name = 'Lincoln Borough' where id = '13';
update service set short_name = 'Lincoln Thomasville' where id = '719';
update service set short_name = 'Lineboro' where id = '720';
update service set short_name = 'Linesville' where id = '721';
update service set short_name = 'Little Meadows' where id = '722';
update service set short_name = 'Liverpool' where id = '723';
update service set short_name = 'Llanerch' where id = '725';
update service set short_name = 'Lock Haven' where id = '726';
update service set short_name = 'Lock VFC' where id = '284';
update service set short_name = 'Londonderry' where id = '727';
update service set short_name = 'Long Life' where id = '728';
update service set short_name = 'Longwood' where id = '729';
update service set short_name = 'Lost Creek' where id = '227';
update service set short_name = 'Lower Allen' where id = '730';
update service set short_name = 'Lower Alsace' where id = '228';
update service set short_name = 'Lower Burrell' where id = '109';
update service set short_name = 'Lower Frederick' where id = '731';
update service set short_name = 'Lower Kiski' where id = '142';
update service set short_name = 'Lower Providence' where id = '732';
update service set short_name = 'Lower Valley' where id = '14';
update service set short_name = 'Loyalsock' where id = '733';
update service set short_name = 'LVHN MedEvac' where id = '225';
update service set short_name = 'MAAT' where id = '765';
update service set short_name = 'Macungie' where id = '229';
update service set short_name = 'Madera' where id = '323';
update service set short_name = 'Mahaffey' where id = '324';
update service set short_name = 'Mahanoy' where id = '230';
update service set short_name = 'Mahantongo' where id = '231';
update service set short_name = 'Mahoning' where id = '232';
update service set short_name = 'Malvern' where id = '734';
update service set short_name = 'Manchester' where id = '736';
update service set short_name = 'Manheim' where id = '737';
update service set short_name = 'Manoa' where id = '738';
update service set short_name = 'Mansfield' where id = '739';
update service set short_name = 'MAPS' where id = '32';
update service set short_name = 'Marclay' where id = '70';
update service set short_name = 'Marion' where id = '740';
update service set short_name = 'Marklesburg' where id = '741';
update service set short_name = 'Marple' where id = '742';
update service set short_name = 'Mars EMS' where id = '146';
update service set short_name = 'Mars Fire' where id = '65';
update service set short_name = 'Marshalls Creek' where id = '233';
update service set short_name = 'Marysville' where id = '743';
update service set short_name = 'MAS' where id = '236';
update service set short_name = 'McAdoo' where id = '234';
update service set short_name = 'McCandless' where id = '22';
update service set short_name = 'McConnellsburg' where id = '744';
update service set short_name = 'McDonald' where id = '125';
update service set short_name = 'MCES' where id = '787';
update service set short_name = 'McGonigle' where id = '745';
update service set short_name = 'McKean' where id = '746';
update service set short_name = 'McKeesport' where id = '30';
update service set short_name = 'McVeytown' where id = '747';
update service set short_name = 'Meadville' where id = '748';
update service set short_name = 'Med Mobile' where id = '235';
update service set short_name = 'Med Plus' where id = '749';
update service set short_name = 'Med Responce' where id = '750';
update service set short_name = 'Med Stat' where id = '751';
update service set short_name = 'Med-Trans' where id = '753';
update service set short_name = 'Med-Van' where id = '724';
update service set short_name = 'MedAlliance' where id = '517';
update service set short_name = 'MedForce' where id = '382';
update service set short_name = 'Media' where id = '754';
update service set short_name = 'Medic Rescue' where id = '51';
update service set short_name = 'MEDICS' where id = '755';
update service set short_name = 'Medstar' where id = '377';
update service set short_name = 'Memorial' where id = '756';
update service set short_name = 'Memorial Hosp York' where id = '1082';
update service set short_name = 'Merck' where id = '758';
update service set short_name = 'Mercy' where id = '759';
update service set short_name = 'Mercy Care' where id = '760';
update service set short_name = 'Mercy Fitzgerald' where id = '761';
update service set short_name = 'Mercy Flight' where id = '345';
update service set short_name = 'Meshoppen' where id = '762';
update service set short_name = 'Metal' where id = '764';
update service set short_name = 'Metro Medics' where id = '757';
update service set short_name = 'Meyersdale' where id = '766';
update service set short_name = 'Mid-State' where id = '947';
update service set short_name = 'MidAtlantic' where id = '752';
update service set short_name = 'Middle Road' where id = '293';
update service set short_name = 'Middlebury' where id = '767';
update service set short_name = 'Midway EMS' where id = '768';
update service set short_name = 'Midway Fire' where id = '97';
update service set short_name = 'Mifflinburg' where id = '769';
update service set short_name = 'Mildred' where id = '770';
update service set short_name = 'Milford' where id = '771';
update service set short_name = 'Mill Village' where id = '772';
update service set short_name = 'Millcreek' where id = '773';
update service set short_name = 'Millennium' where id = '774';
update service set short_name = 'Millersburg' where id = '775';
update service set short_name = 'Millerstown' where id = '776';
update service set short_name = 'Millville' where id = '777';
update service set short_name = 'Milmont' where id = '778';
update service set short_name = 'Milroy' where id = '779';
update service set short_name = 'Milton' where id = '780';
update service set short_name = 'Minersville' where id = '212';
update service set short_name = 'Minquas' where id = '781';
update service set short_name = 'Miracle Care' where id = '782';
update service set short_name = 'MMPW' where id = '783';
update service set short_name = 'Mobile Care' where id = '784';
update service set short_name = 'Mobile Nurse Network' where id = '53';
update service set short_name = 'Modena' where id = '785';
update service set short_name = 'Mon Valley' where id = '110';
update service set short_name = 'Monroeville' where id = '15';
update service set short_name = 'Mont Alto' where id = '786';
update service set short_name = 'Montgomery VFC' where id = '788';
update service set short_name = 'Montrose Minute Men' where id = '789';
update service set short_name = 'Morris FAA' where id = '790';
update service set short_name = 'Morris Twp' where id = '151';
update service set short_name = 'Morrisville' where id = '791';
update service set short_name = 'Moscow' where id = '792';
update service set short_name = 'Moshannon Valley' where id = '793';
update service set short_name = 'Mount Nittany' where id = '794';
update service set short_name = 'Mount Pleasant EMS' where id = '129';
update service set short_name = 'Mount Pleasant Fire' where id = '101';
update service set short_name = 'Mount Union' where id = '795';
update service set short_name = 'Mountain Top Fire' where id = '796';
update service set short_name = 'Mountaintop Amb' where id = '797';
update service set short_name = 'MRTSA' where id = '24';
update service set short_name = 'Mt Jewett' where id = '344';
update service set short_name = 'Mt Lebanon' where id = '315';
update service set short_name = 'Mt Morris' where id = '75';
update service set short_name = 'Mt Oliver' where id = '296';
update service set short_name = 'Muhlenberg' where id = '237';
update service set short_name = 'Muncy Area VFC' where id = '798';
update service set short_name = 'Muncy Twp VFC' where id = '799';
update service set short_name = 'Muncy Valley' where id = '800';
update service set short_name = 'Murrysville' where id = '121';
update service set short_name = 'Murrysville M1' where id = '280';
update service set short_name = 'Mutual Aid' where id = '111';
update service set short_name = 'Myerstown' where id = '801';
update service set short_name = 'Nanticoke' where id = '802';
update service set short_name = 'National Amb' where id = '803';
update service set short_name = 'National Event Svcs' where id = '804';
update service set short_name = 'Nationwide' where id = '238';
update service set short_name = 'Nazareth' where id = '239';
update service set short_name = 'Needmore' where id = '805';
update service set short_name = 'Nemacolin' where id = '77';
update service set short_name = 'Nemours Kids' where id = '806';
update service set short_name = 'Nescopeck' where id = '807';
update service set short_name = 'Nesquehoning' where id = '240';
update service set short_name = 'New Berlin' where id = '808';
update service set short_name = 'New Bloomfield' where id = '809';
update service set short_name = 'New Castle' where id = '158';
update service set short_name = 'New Cumberland' where id = '810';
update service set short_name = 'New Holland' where id = '811';
update service set short_name = 'New Kensington' where id = '112';
update service set short_name = 'New Ringgold' where id = '241';
update service set short_name = 'New Trinity' where id = '812';
update service set short_name = 'New Wilmington' where id = '135';
update service set short_name = 'Newberry' where id = '813';
update service set short_name = 'Newfoundland' where id = '814';
update service set short_name = 'Newmanstown' where id = '815';
update service set short_name = 'Newport' where id = '816';
update service set short_name = 'Newton-Ransom' where id = '817';
update service set short_name = 'Newtown AL' where id = '818';
update service set short_name = 'Newtown Twp' where id = '991';
update service set short_name = 'NOGA' where id = '86';
update service set short_name = 'North Beaver' where id = '136';
update service set short_name = 'North Huntingdon' where id = '113';
update service set short_name = 'North Strabane' where id = '290';
update service set short_name = 'North Washington' where id = '159';
update service set short_name = 'Northampton' where id = '242';
update service set short_name = 'Northeast' where id = '820';
update service set short_name = 'Northeastern' where id = '735';
update service set short_name = 'Northern Lancaster' where id = '821';
update service set short_name = 'Northern Lehigh' where id = '243';
update service set short_name = 'Northern Wayne' where id = '822';
update service set short_name = 'NorthWest' where id = '37';
update service set short_name = 'Northwest EMS Inc' where id = '823';
update service set short_name = 'Northwestern' where id = '50';
update service set short_name = 'Norvelt' where id = '114';
update service set short_name = 'Norwood' where id = '824';
update service set short_name = 'NOVA' where id = '244';
update service set short_name = 'Noxen' where id = '825';
update service set short_name = 'Penn Hills 224' where id = '297';
update service set short_name = 'Penn Hills 222' where id = '301';
update service set short_name = 'Nuremberg' where id = '246';
update service set short_name = 'NWAC' where id = '245';
update service set short_name = 'Oakdale' where id = '40';
update service set short_name = 'Oil City' where id = '827';
update service set short_name = 'Oklahoma' where id = '122';
update service set short_name = 'Old Forge' where id = '828';
update service set short_name = 'Old Lycoming' where id = '829';
update service set short_name = 'Oley' where id = '247';
update service set short_name = 'Olyphant' where id = '830';
update service set short_name = 'Omega' where id = '831';
update service set short_name = 'On Watch' where id = '706';
update service set short_name = 'Orbisonia-Rockhill' where id = '832';
update service set short_name = 'Orwigsburg' where id = '248';
update service set short_name = 'Otto' where id = '341';
update service set short_name = 'PA Med Transport' where id = '84';
update service set short_name = 'Palmerton' where id = '249';
update service set short_name = 'Paoli' where id = '834';
update service set short_name = 'Parkside' where id = '835';
update service set short_name = 'Parkview' where id = '3';
update service set short_name = 'Patton' where id = '836';
update service set short_name = 'Penn Hills' where id = '131';
update service set short_name = 'Penn Hills 221' where id = '306';
update service set short_name = 'Penn Stat' where id = '837';
update service set short_name = 'Penn Twp Amb' where id = '115';
update service set short_name = 'Penn Twp VES' where id = '838';
update service set short_name = 'Penn-Mahoning' where id = '250';
update service set short_name = 'Penndel-Middletown' where id = '839';
update service set short_name = 'Penns Creek' where id = '840';
update service set short_name = 'Penns Valley' where id = '841';
update service set short_name = 'PennSTAR Flight' where id = '1020';
update service set short_name = 'PennStar Haverford' where id = '842';
update service set short_name = 'Pennsylvania Amb' where id = '843';
update service set short_name = 'Perry Hi-Way' where id = '844';
update service set short_name = 'Perryopolis' where id = '71';
update service set short_name = 'Peters Twp Fire' where id = '156';
update service set short_name = 'Peters Twp VFW' where id = '90';
update service set short_name = 'Petrolia' where id = '59';
update service set short_name = 'Philadelphia Fire' where id = '846';
update service set short_name = 'Philadelphia Park' where id = '847';
update service set short_name = 'Picture Rocks' where id = '848';
update service set short_name = 'Pine Grove' where id = '251';
update service set short_name = 'Pine Run' where id = '291';
update service set short_name = 'Pitcairn' where id = '139';
update service set short_name = 'Pittsburgh' where id = '128';
update service set short_name = 'Pittston' where id = '849';
update service set short_name = 'Plainfield' where id = '252';
update service set short_name = 'Plains' where id = '850';
update service set short_name = 'Platea' where id = '851';
update service set short_name = 'Platinum' where id = '852';
update service set short_name = 'Pleasant' where id = '857';
update service set short_name = 'Pleasant Gap' where id = '853';
update service set short_name = 'Pleasant Hall' where id = '854';
update service set short_name = 'Pleasant Hill' where id = '855';
update service set short_name = 'Pleasant Hills' where id = '298';
update service set short_name = 'Pleasant Mount' where id = '856';
update service set short_name = 'Plum' where id = '20';
update service set short_name = 'Plunketts Creek' where id = '858';
update service set short_name = 'Plymouth Amb' where id = '859';
update service set short_name = 'Plymouth Rescue' where id = '860';
update service set short_name = 'PMR Amb' where id = '861';
update service set short_name = 'PMR EMS' where id = '254';
update service set short_name = 'PMR G&T' where id = '599';
update service set short_name = 'Pocono Area' where id = '253';
update service set short_name = 'Point Marion' where id = '72';
update service set short_name = 'Point Pleasant-Plumsteadville' where id = '862';
update service set short_name = 'Pond Hill-Lily Lake' where id = '863';
update service set short_name = 'Port Allegany' where id = '342';
update service set short_name = 'Port Jervis' where id = '864';
update service set short_name = 'Port Matilda' where id = '865';
update service set short_name = 'Port Royal' where id = '866';
update service set short_name = 'Portage' where id = '867';
update service set short_name = 'Portersville' where id = '63';
update service set short_name = 'Pottstown' where id = '868';
update service set short_name = 'Pottsville' where id = '255';
update service set short_name = 'PRA' where id = '638';
update service set short_name = 'Preferred' where id = '869';
update service set short_name = 'Premium Care' where id = '870';
update service set short_name = 'Priority Care' where id = '346';
update service set short_name = 'Priority One' where id = '35';
update service set short_name = 'PRISM' where id = '27';
update service set short_name = 'Pro Medic' where id = '871';
update service set short_name = 'Professional' where id = '963';
update service set short_name = 'Promised Land' where id = '873';
update service set short_name = 'Protrans' where id = '874';
update service set short_name = 'Providers Choice' where id = '875';
update service set short_name = 'PSU' where id = '826';
update service set short_name = 'Pulaski' where id = '137';
update service set short_name = 'Pure Life' where id = '876';
update service set short_name = 'QRMT' where id = '877';
update service set short_name = 'Quaker Valley' where id = '167';
update service set short_name = 'Quality' where id = '64';
update service set short_name = 'QualityStar' where id = '878';
update service set short_name = 'Quick Ride' where id = '879';
update service set short_name = 'Radnor' where id = '880';
update service set short_name = 'Ralston' where id = '881';
update service set short_name = 'Raystown' where id = '882';
update service set short_name = 'Reade' where id = '883';
update service set short_name = 'Reading' where id = '200';
update service set short_name = 'Ready' where id = '884';
update service set short_name = 'Reamstown' where id = '885';
update service set short_name = 'Red Lion' where id = '886';
update service set short_name = 'Regency' where id = '1032';
update service set short_name = 'Regional' where id = '256';
update service set short_name = 'Reinholds' where id = '887';
update service set short_name = 'Reliance' where id = '888';
update service set short_name = 'Reno' where id = '889';
update service set short_name = 'Renton' where id = '302';
update service set short_name = 'Rescue 14 EMS' where id = '118';
update service set short_name = 'Rescue H&L' where id = '320';
update service set short_name = 'Rescue HC' where id = '890';
update service set short_name = 'Rescue HC#1' where id = '891';
update service set short_name = 'Rescue Pro' where id = '892';
update service set short_name = 'Rescue Team' where id = '893';
update service set short_name = 'Rescue Tech' where id = '894';
update service set short_name = 'Respect' where id = '895';
update service set short_name = 'Response' where id = '257';
update service set short_name = 'Reynoldsville' where id = '335';
update service set short_name = 'Rhawnhurst-Bustleton' where id = '896';
update service set short_name = 'Rhythm' where id = '897';
update service set short_name = 'Rices Landing' where id = '78';
update service set short_name = 'Richfield' where id = '898';
update service set short_name = 'Richhill' where id = '81';
update service set short_name = 'Richland' where id = '28';
update service set short_name = 'Riddle' where id = '899';
update service set short_name = 'Ridgway' where id = '330';
update service set short_name = 'Ridley' where id = '900';
update service set short_name = 'Ringtown' where id = '258';
update service set short_name = 'Riverside' where id = '901';
update service set short_name = 'Robinson' where id = '138';
update service set short_name = 'Rockwood' where id = '903';
update service set short_name = 'Rocky Run' where id = '904';
update service set short_name = 'Rodan' where id = '905';
update service set short_name = 'Romed' where id = '906';
update service set short_name = 'Roscoe' where id = '99';
update service set short_name = 'Rose of New Freedom' where id = '907';
update service set short_name = 'Ross/West View' where id = '23';
update service set short_name = 'Rostraver/West Newton' where id = '89';
update service set short_name = 'Rothsville' where id = '908';
update service set short_name = 'Roulette' where id = '348';
update service set short_name = 'Rush' where id = '909';
update service set short_name = 'Russell' where id = '910';
update service set short_name = 'RW&T' where id = '902';
update service set short_name = 'Ryan' where id = '259';
update service set short_name = 'Sabinsville' where id = '911';
update service set short_name = 'Safety First' where id = '912';
update service set short_name = 'Saint Clair' where id = '260';
update service set short_name = 'Saiva' where id = '819';
update service set short_name = 'Salisbury Amb' where id = '913';
update service set short_name = 'Salisbury Twp Fire' where id = '914';
update service set short_name = 'Samaritan' where id = '915';
update service set short_name = 'Saxonburg' where id = '60';
update service set short_name = 'Saxton' where id = '916';
update service set short_name = 'Scandia' where id = '917';
update service set short_name = 'Schaefferstown' where id = '918';
update service set short_name = 'Schuylkill' where id = '261';
update service set short_name = 'Scott Twp Amb' where id = '919';
update service set short_name = 'Scott Twp EMS' where id = '33';
update service set short_name = 'Scott Twp Fire' where id = '153';
update service set short_name = 'Scranton Quincy' where id = '920';
update service set short_name = 'Second Alarmers' where id = '921';
update service set short_name = 'Select' where id = '262';
update service set short_name = 'Seneca' where id = '17';
update service set short_name = 'Sewickley Twp CAS' where id = '104';
update service set short_name = 'Sewickley VFC' where id = '313';
update service set short_name = 'Shaler EMS' where id = '52';
update service set short_name = 'Shaler Villa' where id = '292';
update service set short_name = 'Shawnee Valley' where id = '922';
update service set short_name = 'Sheffield' where id = '923';
update service set short_name = 'Shenandoah' where id = '263';
update service set short_name = 'Shenango' where id = '178';
update service set short_name = 'Shermansdale' where id = '924';
update service set short_name = 'Shickshinny' where id = '925';
update service set short_name = 'Shinglehouse' where id = '352';
update service set short_name = 'Shippensburg' where id = '926';
update service set short_name = 'Shippenville-Elk' where id = '927';
update service set short_name = 'Silver Lake' where id = '928';
update service set short_name = 'Silver Spring' where id = '929';
update service set short_name = 'Sinnamahoning' where id = '317';
update service set short_name = 'Six Mile Run' where id = '930';
update service set short_name = 'Skippack' where id = '931';
update service set short_name = 'Sky' where id = '932';
update service set short_name = 'Slippery Rock' where id = '61';
update service set short_name = 'Slocum' where id = '933';
update service set short_name = 'Smock' where id = '74';
update service set short_name = 'SMRT' where id = '174';
update service set short_name = 'SMT' where id = '962';
update service set short_name = 'Snow Shoe' where id = '934';
update service set short_name = 'Soldiers and Sailors' where id = '935';
update service set short_name = 'Somerset' where id = '936';
update service set short_name = 'Souderton' where id = '937';
update service set short_name = 'South Baldwin' where id = '294';
update service set short_name = 'South Buffalo' where id = '299';
update service set short_name = 'South Butler' where id = '68';
update service set short_name = 'South Central' where id = '938';
update service set short_name = 'South Creek' where id = '939';
update service set short_name = 'South Eastern' where id = '940';
update service set short_name = 'South Mountain' where id = '941';
update service set short_name = 'SouthBridge' where id = '18';
update service set short_name = 'Southeastern Adams' where id = '942';
update service set short_name = 'Southern Berks' where id = '264';
update service set short_name = 'Southern Chester' where id = '943';
update service set short_name = 'Southern Clarion' where id = '944';
update service set short_name = 'Southern Cove' where id = '945';
update service set short_name = 'Spartansburg' where id = '946';
update service set short_name = 'Spellman' where id = '461';
update service set short_name = 'Sports Medic' where id = '281';
update service set short_name = 'Spring Grove' where id = '948';
update service set short_name = 'Springboro' where id = '949';
update service set short_name = 'Springdale' where id = '175';
update service set short_name = 'Springettsbury' where id = '950';
update service set short_name = 'Springfield Assn' where id = '951';
update service set short_name = 'Springfield Corps' where id = '952';
update service set short_name = 'Springfield Fire' where id = '953';
update service set short_name = 'Squad A' where id = '954';
update service set short_name = 'St Lukes' where id = '955';
update service set short_name = 'St Margaret' where id = '42';
update service set short_name = 'St Mary EMS' where id = '956';
update service set short_name = 'St Marys Area Amb' where id = '331';
update service set short_name = 'St Thomas' where id = '957';
update service set short_name = 'Stancliff' where id = '958';
update service set short_name = 'Star Med Amb' where id = '959';
update service set short_name = 'Star Plus' where id = '961';
update service set short_name = 'STARFLIGHT' where id = '1045';
update service set short_name = 'Sturgeon' where id = '165';
update service set short_name = 'Suburban' where id = '265';
update service set short_name = 'Sugar Grove' where id = '964';
update service set short_name = 'Sugarcreek' where id = '169';
update service set short_name = 'Sugarloaf CRAA' where id = '965';
update service set short_name = 'Sugarloaf Fire' where id = '966';
update service set short_name = 'Summerville' where id = '337';
update service set short_name = 'Summit' where id = '967';
update service set short_name = 'SunLife' where id = '968';
update service set short_name = 'Sunny' where id = '969';
update service set short_name = 'Superior' where id = '970';
update service set short_name = 'SuperiorOne' where id = '412';
update service set short_name = 'Susquehanna Fire' where id = '971';
update service set short_name = 'Susquehanna Twp EMS' where id = '972';
update service set short_name = 'Susquehanna Valley' where id = '973';
update service set short_name = 'Swarthmore' where id = '974';
update service set short_name = 'Sweet Valley' where id = '975';
update service set short_name = 'Swissvale' where id = '311';
update service set short_name = 'Swoyersville' where id = '976';
update service set short_name = 'Sykesville' where id = '336';
update service set short_name = 'Tafton' where id = '977';
update service set short_name = 'Tamaqua' where id = '266';
update service set short_name = 'Temple Med Flight' where id = '979';
update service set short_name = 'Temple Transport Team' where id = '978';
update service set short_name = 'Thompson' where id = '980';
update service set short_name = 'Thompsontown' where id = '981';
update service set short_name = 'Thornhurst' where id = '982';
update service set short_name = 'Three Springs' where id = '983';
update service set short_name = 'Tidioute' where id = '984';
update service set short_name = 'Tinicum' where id = '985';
update service set short_name = 'Tioga' where id = '986';
update service set short_name = 'Tionesta' where id = '987';
update service set short_name = 'TLC ALS' where id = '988';
update service set short_name = 'TLC Med Response' where id = '989';
update service set short_name = 'Tobyhanna' where id = '267';
update service set short_name = 'Top of the Line' where id = '990';
update service set short_name = 'Topton' where id = '268';
update service set short_name = 'Tower-Porter' where id = '269';
update service set short_name = 'Townville' where id = '992';
update service set short_name = 'Trafford' where id = '116';
update service set short_name = 'Trans Am' where id = '343';
update service set short_name = 'Trans Mercy' where id = '993';
update service set short_name = 'Trans-Med' where id = '994';
update service set short_name = 'TransCare' where id = '995';
update service set short_name = 'Trappe' where id = '996';
update service set short_name = 'Tremont EMS' where id = '270';
update service set short_name = 'Tremont Transport' where id = '271';
update service set short_name = 'Trevorton' where id = '997';
update service set short_name = 'Tri-Community' where id = '91';
update service set short_name = 'Tri-Community South' where id = '127';
update service set short_name = 'Tri-Community York' where id = '998';
update service set short_name = 'Tri-Hampton' where id = '999';
update service set short_name = 'Tri-Town' where id = '353';
update service set short_name = 'Tri-Twp' where id = '1000';
update service set short_name = 'Triple Aid' where id = '1001';
update service set short_name = 'Tristar' where id = '1002';
update service set short_name = 'Trout Run' where id = '1003';
update service set short_name = 'Trucksville' where id = '1004';
update service set short_name = 'True Care' where id = '1005';
update service set short_name = 'Trust' where id = '1006';
update service set short_name = 'Tunkhannock' where id = '1007';
update service set short_name = 'Tusten' where id = '1008';
update service set short_name = 'Twin Creeks' where id = '1009';
update service set short_name = 'Uni-Med' where id = '1010';
update service set short_name = 'Unicare' where id = '1012';
update service set short_name = 'Union' where id = '171';
update service set short_name = 'Union City' where id = '1013';
update service set short_name = 'Union Co West End' where id = '1014';
update service set short_name = 'Union Fire' where id = '1015';
update service set short_name = 'Union Twp Fire' where id = '148';
update service set short_name = 'United H&L' where id = '1016';
update service set short_name = 'United Medical' where id = '1017';
update service set short_name = 'United Medical Care' where id = '1011';
update service set short_name = 'United VFR' where id = '6';
update service set short_name = 'Unity VFD' where id = '312';
update service set short_name = 'Universal Amb' where id = '1018';
update service set short_name = 'Universal Medical Response' where id = '1019';
update service set short_name = 'Upper Bucks' where id = '1021';
update service set short_name = 'Upper Perkiomen Valley' where id = '1022';
update service set short_name = 'Upper Saucon' where id = '272';
update service set short_name = 'Upper Yoder' where id = '1023';
update service set short_name = 'Utica' where id = '1024';
update service set short_name = 'Uwchlan' where id = '1025';
update service set short_name = 'Valley' where id = '166';
update service set short_name = 'Valley CAA' where id = '1026';
update service set short_name = 'Valley Regional' where id = '1027';
update service set short_name = 'Vandergrift' where id = '117';
update service set short_name = 'Vauclain' where id = '1028';
update service set short_name = 'Villanova' where id = '1030';
update service set short_name = 'VIP' where id = '1031';
update service set short_name = 'VMAS' where id = '1029';
update service set short_name = 'VMSC Lansdale' where id = '1034';
update service set short_name = 'VMSC Lower Merion' where id = '1033';
update service set short_name = 'VOLANT' where id = '87';
update service set short_name = 'Wakefield' where id = '1035';
update service set short_name = 'Warminster' where id = '1036';
update service set short_name = 'Warren' where id = '468';
update service set short_name = 'Warrington' where id = '1037';
update service set short_name = 'Warrior Run' where id = '1038';
update service set short_name = 'Warwick' where id = '1039';
update service set short_name = 'Washington DPS' where id = '162';
update service set short_name = 'Washington FCCA' where id = '273';
update service set short_name = 'Washington Fire' where id = '132';
update service set short_name = 'Washington HC' where id = '1040';
update service set short_name = 'Wattsburg' where id = '1041';
update service set short_name = 'Waymart' where id = '1042';
update service set short_name = 'Waynesboro ALS' where id = '1044';
update service set short_name = 'Waynesboro Amb' where id = '1043';
update service set short_name = 'WCARA' where id = '186';
update service set short_name = 'Weirton' where id = '173';
update service set short_name = 'Welcome' where id = '1046';
update service set short_name = 'Wellsboro' where id = '1047';
update service set short_name = 'WellSpan Ephrata' where id = '1048';
update service set short_name = 'WellSpan Health' where id = '1049';
update service set short_name = 'Wesleyville' where id = '1050';
update service set short_name = 'West Alexander' where id = '94';
update service set short_name = 'West Co' where id = '1051';
update service set short_name = 'West Deer EMS' where id = '140';
update service set short_name = 'West Deer Fire' where id = '163';
update service set short_name = 'West End ASI' where id = '1052';
update service set short_name = 'West End CA' where id = '274';
update service set short_name = 'West End Fire' where id = '1053';
update service set short_name = 'West Finley' where id = '98';
update service set short_name = 'West Grove' where id = '1054';
update service set short_name = 'West Hazleton' where id = '1055';
update service set short_name = 'West Hills' where id = '1056';
update service set short_name = 'West Pittston' where id = '1057';
update service set short_name = 'West Schuylkill' where id = '275';
update service set short_name = 'West Wyoming' where id = '1058';
update service set short_name = 'West York' where id = '1059';
update service set short_name = 'Western Alliance' where id = '1060';
update service set short_name = 'Western Berks' where id = '276';
update service set short_name = 'Westfall' where id = '1061';
update service set short_name = 'Westmoreland' where id = '185';
update service set short_name = 'Westwood' where id = '1062';
update service set short_name = 'White Deer' where id = '1063';
update service set short_name = 'White Haven' where id = '1064';
update service set short_name = 'White Mills' where id = '1065';
update service set short_name = 'White Oak' where id = '29';
update service set short_name = 'White Rose' where id = '396';
update service set short_name = 'Whitehall' where id = '219';
update service set short_name = 'Whitemarsh' where id = '1066';
update service set short_name = 'Wilcox' where id = '332';
update service set short_name = 'Wilkes-Barre' where id = '469';
update service set short_name = 'William Cameron' where id = '1067';
update service set short_name = 'William Walker' where id = '1068';
update service set short_name = 'Williamsburg' where id = '1069';
update service set short_name = 'Williamsport' where id = '1070';
update service set short_name = 'Williamstown' where id = '1071';
update service set short_name = 'Willing Hand' where id = '1072';
update service set short_name = 'Wind Gap' where id = '277';
update service set short_name = 'Windber' where id = '1073';
update service set short_name = 'Wissinoming' where id = '1074';
update service set short_name = 'WoodGroup' where id = '1075';
update service set short_name = 'Woodland Hills' where id = '7';
update service set short_name = 'Woodlyn' where id = '1076';
update service set short_name = 'Wyoming' where id = '1077';
update service set short_name = 'Wysox' where id = '1078';
update service set short_name = 'Yardley-Makefield' where id = '1079';
update service set short_name = 'Yeadon' where id = '1080';
update service set short_name = 'Yellow Breeches' where id = '1081';
update service set short_name = 'York Regional' where id = '1083';
update service set short_name = 'York Springs' where id = '1084';
update service set short_name = 'Youngsville' where id = '1085';
update service set short_name = 'Zelienople' where id = '310';
;
COMMIT