START TRANSACTION
;
ALTER TABLE `county_code_name_map` DROP INDEX `name`
, ADD UNIQUE INDEX `name` (`name` ASC)
;
ALTER TABLE `county_code_name_map` ADD COLUMN `emsrs_code` TINYINT UNSIGNED NOT NULL
;
insert county_code_name_map set name = 'Adams', emsrs_code = '1' on duplicate key update emsrs_code = '1';
insert county_code_name_map set name = 'Allegheny', emsrs_code = '2' on duplicate key update emsrs_code = '2';
insert county_code_name_map set name = 'Armstrong', emsrs_code = '3' on duplicate key update emsrs_code = '3';
insert county_code_name_map set name = 'Beaver', emsrs_code = '4' on duplicate key update emsrs_code = '4';
insert county_code_name_map set name = 'Bedford', emsrs_code = '5' on duplicate key update emsrs_code = '5';
insert county_code_name_map set name = 'Berks', emsrs_code = '6' on duplicate key update emsrs_code = '6';
insert county_code_name_map set name = 'Blair', emsrs_code = '7' on duplicate key update emsrs_code = '7';
insert county_code_name_map set name = 'Bradford', emsrs_code = '8' on duplicate key update emsrs_code = '8';
insert county_code_name_map set name = 'Bucks', emsrs_code = '9' on duplicate key update emsrs_code = '9';
insert county_code_name_map set name = 'Butler', emsrs_code = '10' on duplicate key update emsrs_code = '10';
insert county_code_name_map set name = 'Cambria', emsrs_code = '11' on duplicate key update emsrs_code = '11';
insert county_code_name_map set name = 'Cameron', emsrs_code = '12' on duplicate key update emsrs_code = '12';
insert county_code_name_map set name = 'Carbon', emsrs_code = '13' on duplicate key update emsrs_code = '13';
insert county_code_name_map set name = 'Centre', emsrs_code = '14' on duplicate key update emsrs_code = '14';
insert county_code_name_map set name = 'Chester', emsrs_code = '15' on duplicate key update emsrs_code = '15';
insert county_code_name_map set name = 'Clarion', emsrs_code = '16' on duplicate key update emsrs_code = '16';
insert county_code_name_map set name = 'Clearfield', emsrs_code = '17' on duplicate key update emsrs_code = '17';
insert county_code_name_map set name = 'Clinton', emsrs_code = '18' on duplicate key update emsrs_code = '18';
insert county_code_name_map set name = 'Columbia', emsrs_code = '19' on duplicate key update emsrs_code = '19';
insert county_code_name_map set name = 'Crawford', emsrs_code = '20' on duplicate key update emsrs_code = '20';
insert county_code_name_map set name = 'Cumberland', emsrs_code = '21' on duplicate key update emsrs_code = '21';
insert county_code_name_map set name = 'Dauphin', emsrs_code = '22' on duplicate key update emsrs_code = '22';
insert county_code_name_map set name = 'Delaware', emsrs_code = '23' on duplicate key update emsrs_code = '23';
insert county_code_name_map set name = 'Elk', emsrs_code = '24' on duplicate key update emsrs_code = '24';
insert county_code_name_map set name = 'Erie', emsrs_code = '25' on duplicate key update emsrs_code = '25';
insert county_code_name_map set name = 'Fayette', emsrs_code = '26' on duplicate key update emsrs_code = '26';
insert county_code_name_map set name = 'Forest', emsrs_code = '27' on duplicate key update emsrs_code = '27';
insert county_code_name_map set name = 'Franklin', emsrs_code = '28' on duplicate key update emsrs_code = '28';
insert county_code_name_map set name = 'Fulton', emsrs_code = '29' on duplicate key update emsrs_code = '29';
insert county_code_name_map set name = 'Greene', emsrs_code = '30' on duplicate key update emsrs_code = '30';
insert county_code_name_map set name = 'Huntingdon', emsrs_code = '31' on duplicate key update emsrs_code = '31';
insert county_code_name_map set name = 'Indiana', emsrs_code = '32' on duplicate key update emsrs_code = '32';
insert county_code_name_map set name = 'Jefferson', emsrs_code = '33' on duplicate key update emsrs_code = '33';
insert county_code_name_map set name = 'Juniata', emsrs_code = '34' on duplicate key update emsrs_code = '34';
insert county_code_name_map set name = 'Lackawanna', emsrs_code = '35' on duplicate key update emsrs_code = '35';
insert county_code_name_map set name = 'Lancaster', emsrs_code = '36' on duplicate key update emsrs_code = '36';
insert county_code_name_map set name = 'Lawrence', emsrs_code = '37' on duplicate key update emsrs_code = '37';
insert county_code_name_map set name = 'Lebanon', emsrs_code = '38' on duplicate key update emsrs_code = '38';
insert county_code_name_map set name = 'Lehigh', emsrs_code = '39' on duplicate key update emsrs_code = '39';
insert county_code_name_map set name = 'Luzerne', emsrs_code = '40' on duplicate key update emsrs_code = '40';
insert county_code_name_map set name = 'Lycoming', emsrs_code = '41' on duplicate key update emsrs_code = '41';
insert county_code_name_map set name = 'McKean', emsrs_code = '42' on duplicate key update emsrs_code = '42';
insert county_code_name_map set name = 'Mercer', emsrs_code = '43' on duplicate key update emsrs_code = '43';
insert county_code_name_map set name = 'Mifflin', emsrs_code = '44' on duplicate key update emsrs_code = '44';
insert county_code_name_map set name = 'Monroe', emsrs_code = '45' on duplicate key update emsrs_code = '45';
insert county_code_name_map set name = 'Montgomery', emsrs_code = '46' on duplicate key update emsrs_code = '46';
insert county_code_name_map set name = 'Montour', emsrs_code = '47' on duplicate key update emsrs_code = '47';
insert county_code_name_map set name = 'Northampton', emsrs_code = '48' on duplicate key update emsrs_code = '48';
insert county_code_name_map set name = 'Northumberland', emsrs_code = '49' on duplicate key update emsrs_code = '49';
insert county_code_name_map set name = 'Perry', emsrs_code = '50' on duplicate key update emsrs_code = '50';
insert county_code_name_map set name = 'Philadelphia', emsrs_code = '51' on duplicate key update emsrs_code = '51';
insert county_code_name_map set name = 'Pike', emsrs_code = '52' on duplicate key update emsrs_code = '52';
insert county_code_name_map set name = 'Potter', emsrs_code = '53' on duplicate key update emsrs_code = '53';
insert county_code_name_map set name = 'Schuylkill', emsrs_code = '54' on duplicate key update emsrs_code = '54';
insert county_code_name_map set name = 'Snyder', emsrs_code = '55' on duplicate key update emsrs_code = '55';
insert county_code_name_map set name = 'Somerset', emsrs_code = '56' on duplicate key update emsrs_code = '56';
insert county_code_name_map set name = 'Sullivan', emsrs_code = '57' on duplicate key update emsrs_code = '57';
insert county_code_name_map set name = 'Susquehanna', emsrs_code = '58' on duplicate key update emsrs_code = '58';
insert county_code_name_map set name = 'Tioga', emsrs_code = '59' on duplicate key update emsrs_code = '59';
insert county_code_name_map set name = 'Union', emsrs_code = '60' on duplicate key update emsrs_code = '60';
insert county_code_name_map set name = 'Venango', emsrs_code = '61' on duplicate key update emsrs_code = '61';
insert county_code_name_map set name = 'Warren', emsrs_code = '62' on duplicate key update emsrs_code = '62';
insert county_code_name_map set name = 'Washington', emsrs_code = '63' on duplicate key update emsrs_code = '63';
insert county_code_name_map set name = 'Wayne', emsrs_code = '64' on duplicate key update emsrs_code = '64';
insert county_code_name_map set name = 'Westmoreland', emsrs_code = '65' on duplicate key update emsrs_code = '65';
insert county_code_name_map set name = 'Wyoming', emsrs_code = '66' on duplicate key update emsrs_code = '66';
insert county_code_name_map set name = 'York', emsrs_code = '67' on duplicate key update emsrs_code = '67';
;
ALTER TABLE `county_region_map` ADD UNIQUE INDEX `mapping` (`county_code` ASC, `region_code` ASC)
;
ALTER TABLE `county_region_map` DROP INDEX `county_code`
;
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '1'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '2'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '3'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '4'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '5'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '6'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '7'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '8'), region_code = (select code from region_code_name_map where emsrs_code = '1');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '9'), region_code = (select code from region_code_name_map where emsrs_code = '10');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '10'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '11'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '12'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '13'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '14'), region_code = (select code from region_code_name_map where emsrs_code = '8');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '15'), region_code = (select code from region_code_name_map where emsrs_code = '11');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '16'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '17'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '18'), region_code = (select code from region_code_name_map where emsrs_code = '8');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '19'), region_code = (select code from region_code_name_map where emsrs_code = '15');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '20'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '21'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '22'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '23'), region_code = (select code from region_code_name_map where emsrs_code = '12');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '24'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '25'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '26'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '27'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '28'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '29'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '30'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '31'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '32'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '33'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '34'), region_code = (select code from region_code_name_map where emsrs_code = '8');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '35'), region_code = (select code from region_code_name_map where emsrs_code = '5');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '36'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '37'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '38'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '39'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '40'), region_code = (select code from region_code_name_map where emsrs_code = '5');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '41'), region_code = (select code from region_code_name_map where emsrs_code = '7');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '42'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '43'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '44'), region_code = (select code from region_code_name_map where emsrs_code = '8');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '45'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '46'), region_code = (select code from region_code_name_map where emsrs_code = '13');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '47'), region_code = (select code from region_code_name_map where emsrs_code = '15');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '48'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '49'), region_code = (select code from region_code_name_map where emsrs_code = '15');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '50'), region_code = (select code from region_code_name_map where emsrs_code = '3');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '51'), region_code = (select code from region_code_name_map where emsrs_code = '14');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '52'), region_code = (select code from region_code_name_map where emsrs_code = '5');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '53'), region_code = (select code from region_code_name_map where emsrs_code = '19');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '54'), region_code = (select code from region_code_name_map where emsrs_code = '2');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '55'), region_code = (select code from region_code_name_map where emsrs_code = '15');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '56'), region_code = (select code from region_code_name_map where emsrs_code = '9');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '57'), region_code = (select code from region_code_name_map where emsrs_code = '7');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '58'), region_code = (select code from region_code_name_map where emsrs_code = '1');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '59'), region_code = (select code from region_code_name_map where emsrs_code = '7');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '60'), region_code = (select code from region_code_name_map where emsrs_code = '15');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '61'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '62'), region_code = (select code from region_code_name_map where emsrs_code = '18');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '63'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '64'), region_code = (select code from region_code_name_map where emsrs_code = '5');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '65'), region_code = (select code from region_code_name_map where emsrs_code = '4');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '66'), region_code = (select code from region_code_name_map where emsrs_code = '5');
insert ignore county_region_map set county_code = (select code from county_code_name_map where emsrs_code = '67'), region_code = (select code from region_code_name_map where emsrs_code = '3');
;
ALTER TABLE `county_code_name_map` ADD UNIQUE INDEX `emsrs_code` (`emsrs_code` ASC)
;
COMMIT