START TRANSACTION
;
update practitioner set be_instructor = TRUE where id = '2392';
update practitioner set be_instructor = TRUE where id = '3949';
update practitioner set be_instructor = TRUE where id = '3950';
update practitioner set be_instructor = TRUE where id = '4618';
update practitioner set be_instructor = TRUE where id = '5604';
update practitioner set be_instructor = TRUE where id = '45478';
update practitioner set be_instructor = TRUE where id = '45590';
update practitioner set be_instructor = TRUE where id = '48120';
update practitioner set be_instructor = TRUE where id = '51143';
update practitioner set be_instructor = TRUE where id = '54640';
update practitioner set be_instructor = TRUE where id = '574702';
update practitioner set be_instructor = TRUE where id = '611345';
update practitioner set be_instructor = TRUE where id = '646640';
update practitioner set be_instructor = TRUE where id = '1177872';
update practitioner set be_instructor = TRUE where id = '1208222';
update practitioner set be_instructor = TRUE where id = '1208410';
update practitioner set be_instructor = TRUE where id = '1208886';
update practitioner set be_instructor = TRUE where id = '1212740';
update practitioner set be_instructor = TRUE where id = '1217219';
update practitioner set be_instructor = TRUE where id = '1220689';
update practitioner set be_instructor = TRUE where id = '1221116';
update practitioner set be_instructor = TRUE where id = '1221817';
update practitioner set be_instructor = TRUE where id = '1223461';
update practitioner set be_instructor = TRUE where id = '1229622';
update practitioner set be_instructor = TRUE where id = '1229797';
update practitioner set be_instructor = TRUE where id = '1230095';
update practitioner set be_instructor = TRUE where id = '1230601';
update practitioner set be_instructor = TRUE where id = '1231522';
update practitioner set be_instructor = TRUE where id = '1233109';
update practitioner set be_instructor = TRUE where id = '1235876';
update practitioner set be_instructor = TRUE where id = '1236785';
update practitioner set be_instructor = TRUE where id = '1237836';
update practitioner set be_instructor = TRUE where id = '1240136';
update practitioner set be_instructor = TRUE where id = '1243540';
update practitioner set be_instructor = TRUE where id = '1243815';
update practitioner set be_instructor = TRUE where id = '1249417';
;
COMMIT